### ISSUE TITLE
Project.create_pipfile() forces the Pipfile name/path

### ISSUE THREAD

**Issue by hrbonz** [kennethreitz/pipenv#1017]
Reading the code while working on a PR (#1008), I was trying to write a test and realized that `Project.create_pipfile()` forces the [name to `Pipfile`](https://github.com/kennethreitz/pipenv/blob/master/pipenv/project.py#L390) instead of relying on the clever `Project.pipfile_location()` property. There is no reason as far as I can tell but I might be missing something as I'm still a bit new on this project.

**Comment by hrbonz** [comment]
This also makes testing `Project.create_pipfile()` a bit harder.

**Comment by nateprewitt** [comment]
@hrbonz I'm not entirely sure I follow what you're asking. It wouldn't conceptually make sense for create_pipfile to rely on pipfile_location because the pipfile doesn't exist yet. Even if it will mechanically work, you're creating unnecessary coupling in an area it probably doesn't belong.

If you're discussing implementing the PIPENV_PIPFILE check inside of create_pipfile, that may be something we could look at. What are the difficulties you're having with testing?

**Comment by erinxocon** [comment]
It looks like we have a discussion about related topics going on in #1008.  Going to close for cleanup.
