### ISSUE TITLE
How to set default configuration of Pipfile [[source]]

### ISSUE THREAD

**Issue by zeromake** [kennethreitz/pipenv#1040]
I dont find set defaults [[source]] in Pipfile

~~create Pipfile is `pipenv install xxx`,~~
I find create Pipfile and dont install: `pipenv --three`
but I in gfw [pypi](https://pypi.python.org/simple) is not access

##### Describe your environment

1. linux x86_64
1. Python version: 3.6.3
1. Pipenv version: 8.3.1

#### suggest
1. ~~add `pipenv init` create virtualenv and `Pipenv` file， dont install package~~
2. add `[script]` in `Pipenv` file, and node `package.json` same

**Comment by techalchemy** [comment]
Hi @zeromake, thanks for submitting this issue.  it is not currently configurable to set a default source besides pypi, but you can replace the pypi section with your desired source for now

**Comment by wonderbeyond** [comment]
I have a custom `index-url` in my `pip.conf`:

```shell
$ cat ~/.pip/pip.conf
[global]
# index-url = https://pypi.python.org/simple
index-url = https://mirrors.aliyun.com/pypi/simple
# https://pypi.douban.com/simple 
# https://pypi.mirrors.ustc.edu.cn/simple 
# https://pypi.tuna.tsinghua.edu.cn/simple 
# https://pypi.zenlogic.net/simple/ 
```

Can `pipenv` use it while generating a `Pipfile`

**Comment by zeromake** [comment]
@wonderbeyond I needed is defaults set Pipfile
`cat ~/.pip/pip.conf`
``` bash
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
```
`pipenv --two && cat ./Pipfile `
``` bash
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"
```
Not used source of ~/.pip/pip.conf

**Comment by hynek** [comment]
Is there a practical reason why pipenv ignores the default global or did just nobody get around to it?  It’s super tedious to bootstrap projects that contain packages that only exist in our private index.

**Comment by nateprewitt** [comment]
@hynek, this wasn't a deliberate design choice, just how things had been built up to this point.

I don't think there's a technical reason we can't try to parse this, we just need to add the plumbing to do it.

**Comment by hynek** [comment]
So I think this could be done in 1–3 steps that are kind of independent:

1. The simplest first step that would make many people happy is to introduce an env variable like `PIPENV_DEFAULT_PYPI_INDEX` and use that one if it is set.
1. Introduce some kind of magic value (`pip-default`? naming is hard) for it that fetches the pypi default from `~/.pip/pip.conf` / wherever that file is on Windows /  `PIP_INDEX_URL`.
1. The final nice step would be to add a `--pypi-index` option to `pipenv install` which is a bit more work but the payoff would be that you could set the index while installing packages which could be handy if you use multiple index servers.

I could provide you with a PR for 1 if such a feature would be accepted.

**Comment by techalchemy** [comment]
We’d want to use pip’s existing environment variable and fall back to pypi. Pip-tools has functionality internally to retrieve this which I have sitting opened in my browser

**Comment by zeromake** [comment]
@kennethreitz this issues is close, already possible set defaults [[source]] in Pipfile?

**Comment by kennethreitz** [comment]
not in scope

**Comment by hynek** [comment]
Maybe I'm missing something, but if that is not in scope, what concrete bootstrapping workflow do you suggest to everyone who needs to use exclusively a private PyPI because of corporate policies/private packages?  Currently I have to either start with an empty `pipenv install` and hand-edit the file or copy an empty Pipenv file around. 

That seems hardly appropriate for a tool whose ambition is to be the ”the officially recommended Python packaging tool from Python.org“. :(

**Comment by kennethreitz** [comment]
we'll prob honor an environment variable at some point, but we have higher
priorities at the moment. this is on our radar, no worries.

**Comment by mxk** [comment]
I got around this problem by defining PIP_EXTRA_INDEX_URL env variable. PIP_INDEX_URL didn't work because of the -i option that pipenv passes to pip.

Our repo requires individual usernames and passwords, which are part of the URL, so it can't be added to Pipfile. Using an environment variable for this seems to be the best option.

**Comment by kennethreitz** [comment]
@hynek What pip config setting to you expect the default for Pipfile to use?

**Comment by hynek** [comment]
I think the most important one by far is the possibility to have a default index-server.  Most people who have Python as part of their infrastructure run their own PyPI for both performance (it’s no coincidence that the person opening this issue is from China I think) and the ability to have private packages.

Basically honor env `PIP_INDEX_URL` and/or `index-url` in pip.conf.

**Comment by kennethreitz** [comment]
Let's see if we can find where pip has this in memory and just utilize that if it's available.

**Comment by eromoe** [comment]
It is very inconvient to use pipenv in China. Because pypi is super slow here ,we have use a mirror hosted in China. So I have to modify Pipfile every time created a env.

**Comment by uranusjr** [comment]
@eromoe Please refer to #2075, which implements `--pypi-mirror` to let users override PyPI URL at runtime. This is not an issue anymore.
