### ISSUE TITLE
No visual feedback virtualenv (pipenv shell) Windows

### ISSUE THREAD

**Issue by BenjaVR** [kennethreitz/pipenv#1046]
When I 'activate' a virtualenv in my command prompt / powershell / git bash, I don't see a prefix if it's activated or not.

##### Describe your environment

1. Windows
1. Python version: Python 3.6.3
1. Pipenv version: pipenv, version 8.3.2

##### Expected result

```
C:\Users\benja\Dev\Test-Project>pipenv shell
Launching subshell in virtual environment. Type 'exit' to return.
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\benja\Dev\Test-Project>
```

##### Actual result

```
C:\Users\benja\Dev\Test-Project>pipenv shell
Launching subshell in virtual environment. Type 'exit' to return.
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

(Test-Project-Venv) C:\Users\benja\Dev\Test-Project>
```

##### Steps to replicate

Just execute `pipenv shell` in a directory where you installed/enabed pipenv.

**Comment by techalchemy** [comment]
@BenjaVR  thanks for the feedback, this is because pipenv doesn't `source` the virtualenv.  See these for more info:

https://github.com/kennethreitz/pipenv/issues/1036#issuecomment-342666411 #880 

We don't currently have any plans to support this unfortunately, so I'm going to go ahead and close this out

**Comment by Rabia23** [comment]
The issue still persists :( There should be some visual feedback on windows too as it appears in macOS.
