### ISSUE TITLE
Warning: the which -a system utility is required for Pipenv to find Python installations properly.  Please install it.

### ISSUE THREAD

**Issue by wvxvw** [kennethreitz/pipenv#1048]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. Ubuntu 17
1. Python version: `Python 2.7.13`
1. Pipenv version: `pipenv, version 8.3.2`

##### Expected result

I don't really know what this is supposed to do, but this leads to further errors. Also, quite obviously, the error message didn't interpolate values correctly.

##### Actual result

```
Error: the command sphinx-build could not be found within PATH.
```

##### Steps to replicate

I'm trying to execute `pipenv run sphinx-build` from a SCons file, which is executed by calling `pipenv run scons`.  Obviously, `sphinx-build` is installed in the virtual environment of the project where this is being run.

**Comment by techalchemy** [comment]
Hi again @wvxvw thanks for the report. This is not how pipenv works, you can’t call it to run something from _inside_ a virtualenv it is managing. Pipenv is installed externally to the virtualenv, which means you use `pipenv run` the same way you use `pipenv install` — without ever activating the environment directly. That’s part of the reason why pipenv exists, so that you won’t have to activate environments or even worry about where they might be— this is handled for you. 

Since `pipenv` isn’t installed inside the environments it manages, this makes sense.  I’m going to close this issue since it’s not a problem with pipenv and since this information is covered in a bunch of other issues

**Comment by wvxvw** [comment]
Well, the way you describe how you intended for `pipenv` to work, it fails to do that at all. If you tried to call `sphinx-build` from `SCons` installed with `pipenv` in its virtual environment, `SCons` would never have found it. `pipenv run` does exactly nothing to make that happen.  What is the point of using `pipenv run` if nothing run in this way by `pipenv` will be able to find the scripts or packages installed by `pipenv`?

I mean, I'm not happy with `virtualenv`, but at least I can understand the contract: one must set up the shell variables and then run programs in the shell with those variables set to the values that allow locating of scripts and packages. This is clunky, very error prone, non-modular and many other bad things you can imagine... but at least it kind of makes sense. This is while `pipenv run` is virtually useless...

Anyhow, this is again a misunderstanding of the problem on your side: regardless of what you think `pipenv run` should do, the error message generated is meaningless / is a mistake.

**Comment by techalchemy** [comment]
> What is the point of using `pipenv run` if nothing run in this way by pipenv will be able to find the scripts or packages installed by pipenv?

I’m only going to say that you need to read the documentation instead of wasting anymore of the maintainers energy. Obviously `pipenv run` does access the executables it installs _inside the virtualenv it manages_. If it doesn’t manage one, it doesn’t access those.
