### ISSUE TITLE
new command for making alias of the virtual environment directory

### ISSUE THREAD

**Issue by casouri** [kennethreitz/pipenv#1052]
When I use emacs, I can activate virtual environment by point to venv dir. But it is harder when I use pipenv since it's venv dir is deep in .local/. 
Could there be a command like ```pipenv link venv``` that is similar to ```ln -s ~/.local/share/virtualenvs/some-venv venv```?
I am sure others will find this useful to have a alias of venv in root dir

**Comment by casouri** [comment]
I tried looking into cli.py but it is too complicated for me : P

**Comment by techalchemy** [comment]
You control where pipenv puts virtualenvs with the environment variable `WORKON_HOME`, same as is used by `virtualenvwrapper` and other tools (we use `pew` to manage virtualenvs since it is cross platform).

Alternatively you can set the environment variable `PIPENV_VENV_IN_PROJECT` and pipenv will always put the virtualenv you create in `./.venv` in the project root directory.

**Comment by techalchemy** [comment]
Also since we are cross platform and windows doesn't support symlinks I don't see this ever being something we will support.  But if you need to create a symlink you can do that yourself with `ln -s $(pipenv --venv) <wherever you want to put it>` 

I'm going to close this for now since we probably won't do this

```console
 ~/git  pipenv --help
Usage: pipenv [OPTIONS] COMMAND [ARGS]...

Options:
  --update         Update Pipenv & pip to latest.
  --where          Output project home information.
  --venv           Output virtualenv information.
```

**Comment by casouri** [comment]
Thanks!
