### ISSUE TITLE
pipenv install -r requirements.txt

### ISSUE THREAD

**Issue by fruch** [kennethreitz/pipenv#11]
So we could easily migrate for pip based only setup ?

**Comment by kennethreitz** [comment]
Added!

**Comment by fruch** [comment]
You're quick...

**Comment by fruch** [comment]
A bit naive implementation..., does pip have some function that can be used ? or copied ?

**Comment by kennethreitz** [comment]
this works well, for now... need to remove lines that start with a `#`

**Comment by fruch** [comment]
Maybe this can be used ?
https://github.com/davidfischer/requirements-parser/blob/master/README.rst

**Comment by fruch** [comment]
Can help in converting to pipfile systanx of VCS based requirements

**Comment by kennethreitz** [comment]
No need for that, unless it supports `--editable`

**Comment by kennethreitz** [comment]
using it now! much better :)

**Comment by niedzielski** [comment]
Either I've botched something or this isn't working:

```
$ pipenv --version
pipenv, version 3.5.4

$ pipenv install -r requirements.txt 
Error: no such option: -r

$ pipenv install --help
Usage: pipenv install [OPTIONS] [PACKAGE_NAME] [MORE_PACKAGES]...

  Installs provided packages and adds them to Pipfile, or (if none is
  given), installs all packages.

Options:
  -d, --dev        Install package(s) in [dev-packages].
  --three / --two  Use Python 3/2 when creating virtualenv.
  --python TEXT    Specify which version of Python virtualenv should use.
  --system         System pip management.
  --lock           Lock afterwards.
  --no-hashes      Do not generate hashes, if locking.
  --ignore-hashes  Ignore hashes when installing.
  --help           Show this message and exit.
```

**Comment by nateprewitt** [comment]
Hey @niedzielski, `pipenv install -r requirements.txt` was removed fairly early on in the development of `pipenv`. It hasn't been supported since the first week of the project being launched. You'll need to use the new Pipfile format to handle dependencies. If you NEED a requirements.txt for some reason, you can use `pipenv lock -r` to generate requirements.txt compatible output to the console.

**Comment by Paul-Yuchao-Dong** [comment]
First off, great utility and pipenv advances the package management system of python by miles!

However, I want to argue for adding back the `pipenv install -r requirements.txt` command. The use case is when you clone a repo and want to work on a project that don't have pipfile included, you can just run `pipenv install -r requirements.txt` and generate a pipfile that could be used by others in the future.

**Comment by nateprewitt** [comment]
Hey @Paul-Yuchao-Dong, thanks for checking in on this. I still don't see us reintroducing this feature due to the pains it's caused previously. This will usually be a one time only conversion that *should* become a less common as Pipfile becomes more prevalent.

Below is a pretty simple script to do the conversion for you if this needs to be automated.

```python
from pipenv.project import Project
from pipenv.utils import convert_deps_from_pip

with open('requirements.txt', 'r') as f:
    packages = [p for p in f.read().split('\n') if p != '']

pipfile = {'packages': {}}
for package in packages:
    dep = convert_deps_from_pip(package)
    pipfile['packages'].update(dep)

Project().write_toml(pipfile)
```

**Comment by Paul-Yuchao-Dong** [comment]
Wow I didn't realize two things 1) there's seems a painful memory on this feature, 2) pipenv has a python API (I know how stupid it sounds - but I always registered it as a CLI tool, like npm).

Thanks!

**Comment by jacebrowning** [comment]
I would also love to have this feature for the use case of working on project forks.

I can't convince every maintainer to add a `Pipfile` nor do I want to have to continuously ignore pipenv files when I commit. It would be amazing to be able to check out any random Python project and `pipenv install -r requirements.txt`.

**Comment by niedzielski** [comment]
I'm not sure if this is correct but the workaround I've started using for the many pip-only projects out there is `xargs -rd\\n pipenv install < requirements.txt`. (You can probably also get away with `pipenv install $(< requirements.txt)`.)

**Comment by Blue-Dog-Archolite** [comment]
For those of you looking for a solution to this, I created a little pip package. 

https://pypi.python.org/pypi/pipenv-package-requirements/0.1.1

**Comment by sschuberth** [comment]
> This will usually be a one time only conversion that *should* become a less common as Pipfile becomes more prevalent.

@nateprewitt, the point is that Pipfile will probably not become much more relevant (at least for legacy projects) unless you offer an easy migration path.

> Below is a pretty simple script to do the conversion

So on the one hand you're saying the feature caused pain previously, on the other hand you say a simple script can do the conversion, which does not quite match up for me.

In any case, it's better to go through the pain once and solve the problem once in Pipenv rather than requiring everyone who wants to migrate to solve the problem over an over again. Gradle is a good example, whose `init` task is able to [migrate from Maven](https://guides.gradle.org/migrating-from-maven/) (as good as possible). And there *is* demand for this feature, also see https://github.com/kennethreitz/pipenv/issues/165.

**Comment by nateprewitt** [comment]
@sschuberth, thanks for your interest in Pipenv! So this comment you're referring to is 5 months, and 4 major versions, old. This was a pain point in the first couple months of this project and has since been resolved.

Pipenv will now ingest and convert your requirements.txt automatically. You can a link to [the relevant documentation](http://docs.pipenv.org/en/latest/advanced.html#importing-from-requirements-txt) on the front page of http://pipenv.org.

**Comment by sschuberth** [comment]
That for that pointer @nateprewitt! I just tried it, but it seems `-i` / `--index-url` inside `requirements.txt` are not supported. At least pipenv "Could not find a version that satisfies the requirement" for packages that are on a private PyPI server only. Indeed, the index URL from `requirements.txt` is not used as a `[[source]]` URL in Pipfile, it's still hard-coded to `url = "https://pypi.python.org/simple"` is that a known issue?

**Comment by nateprewitt** [comment]
@sschuberth hmm, I'm not sure what Kenneth's current stance on private repo support is. We had it at one point but then it was reverted. I don't think we're explicitly adding sources during the conversion process, so that use case may very well not be working.

If you wouldn't mind opening a new issue with some concrete examples, we can track it from there. This issue is quite old and probably isn't the best place to continue this discussion. Thanks!

**Comment by sschuberth** [comment]
> If you wouldn't mind opening a new issue with some concrete examples, we can track it from there.

@nateprewitt, done: https://github.com/kennethreitz/pipenv/issues/625

**Comment by DrOzturk** [comment]
pipenv already uses the requirements.txt if no Pipfile is there!
(in response to some comments about checking a repo with requirements.txt)
