### ISSUE TITLE
Installing a package with a hyphen results in picking the wrong package

### ISSUE THREAD

**Issue by rjpower** [kennethreitz/pipenv#117]
This doesn't seem consistent, but it appears that pipenv is looking up packages differently than `pip`.  e.g. `msgpack-python` fails to install, but `google-api-python-client` works fine (resolving to the version with all underscores).

```
± pipenv install msgpack-python
Installing msgpack...
Collecting msgpack

Error:  An error occurred while installing msgpack!
  Could not find a version that satisfies the requirement msgpack (from versions: )
No matching distribution found for msgpack
```

**Comment by nateprewitt** [comment]
Thanks for opening this @rjpower, this is in fact a byproduct of a bigger issue noted in #90, which I'm currently working on addressing. Due to some inconsistencies in how we're interacting with the pypi repository, certain packages are experiencing name mangling. We should hopefully have a fix for this soon.

**Comment by kennethreitz** [comment]
Closing for #90
