### ISSUE TITLE
find a way to fix toml output for dicts

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#193]
for example

```
[packages]
flask = "*"
gunicorn = "*"
pyjwt = "*"
requests = "*"
psycopg2 = "*"
records = "*"
docopt = "*"
sendgrid = "*"
auth0-python = "*"

[packages.raven]
extras = [ "flask",]
```

should be 

```
[packages]
flask = "*"
gunicorn = "*"
pyjwt = "*"
requests = "*"
psycopg2 = "*"
records = "*"
docopt = "*"
sendgrid = "*"
auth0-python = "*"
raven = {extras = ["flask,]}
```

**Comment by nateprewitt** [comment]
It looks like the second example isn't actually valid TOML. If we are going to run the normalized output back through `toml.dumps` we're going to get the top output.

I know the latter is how things are documented for `Pipfile`, and we currently support loading it, but can't reliably serialize back to it. Unless we want to start supporting our own variant of TOML we may be hooked for the [package.x] syntax.

Otherwise, we could set aside the keys with dictionary values and then write those separately after the output from `toml.dumps` is written.

**Comment by kennethreitz** [comment]
it is valid toml, there are just multiple ways of representing it, and the serializer is picking our unprepared method.

**Comment by kennethreitz** [comment]
https://github.com/toml-lang/toml#inline-table

**Comment by kennethreitz** [comment]
https://github.com/jumpscale7/python-consistent-toml

**Comment by nateprewitt** [comment]
Ah, missed that section. The only TOML validator I could find was complaining about the syntax. `contoml` seems like a reasonable alternative.

**Comment by kennethreitz** [comment]
having issues with contoml. looking into this now: 

https://github.com/jumpscale7/python-pretty-toml

**Comment by kennethreitz** [comment]
they all suck

**Comment by kennethreitz** [comment]
i give up

**Comment by nateprewitt** [comment]
Pending the acceptance of uiri/toml#75, we may be able to support this. I'm going to reopen this until we get a verdict there.

**Comment by kennethreitz** [comment]
Great work! I was going to do this today :)

**Comment by nateprewitt** [comment]
Ok, a month on and I've finally got this patch working for all scenarios. Hopefully we get a response from uiri soon and will have this resolved in the next release.

**Comment by kennethreitz** [comment]
💫✨🍰✨💫

**Comment by nateprewitt** [comment]
Alright uiri/toml#75 has been merged into the master branch for uiri/toml so we'll get this in the next release. Since we're vendoring this in already, do you have any issue with us adding in the copy from their master @kennethreitz? It seems like it could be a while before we see a release given the previous responsiveness of the project.

**Comment by kennethreitz** [comment]
I did it! ✨🍰✨
