### ISSUE TITLE
$ pipenv run --no-interactive

### ISSUE THREAD

**Issue by relwell** [kennethreitz/pipenv#199]
For example, with Docker:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==3.3.6', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 962, in run
    c.interact()
  File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 740, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by nateprewitt** [comment]
`pipenv` needs a tty in order to function currently, and it appears Docker may not provide that in all cases. There seems to be some open bugs (e.g. #8755) in docker relating to other commands that can't or previously haven't been able to run because of this. I'm not sure if we can support this at the moment but I'll leave it open for a bit while I look into possible options.

**Comment by kennethreitz** [comment]
which command were you running when you got this?

**Comment by relwell** [comment]
Thanks, Kenneth. I had set up a pip env inside of a Dockerfile, and was running the command `pipenv run app.py` on a flask app.

**Comment by kennethreitz** [comment]
interesting. you can always use `pipenv --venv` to find the paths and run the commands manually, in the meantime.

**Comment by kennethreitz** [comment]
or perhaps we can add a flag to `run` (e.g. `$ pipenv run pytest --which`), which would output the path to the executable, for environments like Docker.

**Comment by relwell** [comment]
How about a `--no-interactive` flag that doesn't open a new shell?

**Comment by kennethreitz** [comment]
i like that idea.

**Comment by kennethreitz** [comment]
otherwise, we'll just have to run the process and block until it completes, then show the output.

**Comment by jayfk** [comment]
> How about a `--no-interactive` flag that doesn't open a new shell?

Ideally, you'd just want an entrypoint that activates the virtualenv for you. I was about to write a blog post about this. It's not finished yet, but the `Dockerfile` works: https://pyup.io/posts/pipfiles-and-docker/

This has the great advantage that no matter how you run the container, the virtualenv is already activated.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/cfa4060d8e562681e1ef91e326f28e3508417b3e

**Comment by marioBZ7** [comment]
is this working on the latest release of pipenv? I'm having the same problem, even when trying to spawn a virtual env form jenkins.

**Comment by techalchemy** [comment]
@marioBZ7 the environment variable you want is `PIPENV_YES`

**Comment by marioBZ7** [comment]
I don't know what you're talking about. Right now my problem is when spawning a virtual env from the Dockerfile. At the end of the file I have this line: `CMD ./startup.sh` which should start the virtual env but I'm having the same issue of this tread.

**Comment by techalchemy** [comment]
@marioBZ7 sorry, I didn't realize the issue with 'interactivity' isn't that you don't want to give input (which is what `PIPENV_YES` addresses) but instead that you just need to use pipenv in docker.

> I don't know what you're talking about

I would ask that you be a bit courteous, we are triaging a lot of issues and since most of them come down to a simple answer we don't always invest a lot of time in each one.

[This](https://federschmidt.xyz/python/docker/docker-pipenv/) is a decent overview of how to use pipenv in docker, but essentially you will want to pass `--system` to prevent the creation of a virtualenv at all.

**Comment by dpinol** [comment]
--no-interactive is still required for running pipenv from nohup.

btw, @techalchemy https://federschmidt.xyz/python/docker/docker-pipenv/ is broken

thanks
