### ISSUE TITLE
Unable to install due to blindspin

### ISSUE THREAD

**Issue by sureshvv** [kennethreitz/pipenv#220]
Collecting blindspin (from pipenv)
  Downloading blindspin-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7_qm6osu/blindspin/setup.py", line 7, in <module>
        readme = f.read()
      File "/home/s/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 189: ordinal not in range(128)

**Comment by nateprewitt** [comment]
I'm not entirely sure how you're encountering this, @sureshvv. The stacktrace is suggesting Python3.5 is trying to decode blindspin's `README.rst` as ascii instead of unicode. When doing so, it fails on a character `0xe2` (`â` in utf-8) which doesn't appear to exist in `README.rst`.

Could you please provide the exact command you're using to install, along with your pip version?

**Comment by sureshvv** [comment]
suresh@ssdnodes-server1:~$ pip install pipenv
Collecting pipenv
  Using cached pipenv-3.3.6.tar.gz
Requirement already satisfied: crayons in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: toml in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: click>=6.7 in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: click-completion in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: pip in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: parse in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: virtualenv in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: delegator.py>=0.0.6 in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: requirements-parser in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: pexpect in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: pipfile==0.0.1 in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: requests>=2.4.0 in ./lib/python3.5/site-packages (from pipenv)
Requirement already satisfied: pew>=0.1.26 in ./lib/python3.5/site-packages (from pipenv)
Collecting blindspin (from pipenv)
  Using cached blindspin-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d7bxza2j/blindspin/setup.py", line 7, in <module>
        readme = f.read()
      File "/home/suresh/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 189: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d7bxza2j/blindspin/
suresh@ssdnodes-server1:~$ pip -V
pip 9.0.1 from /home/suresh/lib/python3.5/site-packages (python 3.5)

**Comment by sureshvv** [comment]
Could this be because of some incorrect locale setting?

**Comment by nateprewitt** [comment]
Yep, that does appear to be the issue. Certain systems have ASCII set up for their default locale which Python 3 will use on reading files. The unicode guarantee is only for strings in source code according to this [Stackoverflow Question](http://stackoverflow.com/a/23917799/1575496).

This seems like a fairly odd choice for a linux distro though given the likelihood of `latin-1` or `utf-8` filenames. Out of curiosity what linux distro/version are you running?

My current suggestion here is probably to modify the `PYTHONIOENCODING` environment variable to support utf-8 unless there's a specific reason your distro can't handle it. We can look into patching this in blindspin if it's a common problem but this *seems* like it likely won't be. I'm also unsure how it's even finding `0xe2` in the README.rst because I can't seem to find it locally on my system.

**Comment by sureshvv** [comment]
I found that it was due to my locale.

I changed /etc/environment to contain

LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8

and rebooted. 

Now it works ok!

**Comment by nateprewitt** [comment]
Glad that helped @sureshvv!
