### ISSUE TITLE
pipenv --two installs 3.5 anyway

### ISSUE THREAD

**Issue by debdude** [kennethreitz/pipenv#236]
```
d@MacBook-Pro-d:~/t/unrealcv$ pipenv --two install
Creating a virtualenv for this project...
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in /Volumes/data/home/d/t/unrealcv/.venv/bin/python3.5
Also creating executable in /Volumes/data/home/d/t/unrealcv/.venv/bin/python
Installing setuptools, pip, wheel...done.
```

**Comment by nateprewitt** [comment]
@debdude can you tell me where your system python2 link is pointing?

**Comment by debdude** [comment]
```
d@MacBook-Pro-d:~/t/unrealcv$ which python2
/usr/bin/python2

**Comment by nateprewitt** [comment]
Hmm, it looks like we *may* not be handling the --two/--three param correctly for this scenario. I'm not at a computer to verify right now but I'll take a look this afternoon.

This particular paradigm of initializing the environment and then installing everything seems like it could be useful but isn't really our current intended workflow. Usually you'd run the intialization (pipenv --two) and then install (pipenv install). That's what I'll suggest for now until I can look into this.

**Comment by debdude** [comment]
I can confirm that pipenv --two works as intended, however
```
$ pipenv
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
```
means that COMMAND is mandatory so it never occurred to me to run simply `pipenv --two`, and neither is it mentioned in the README. Maybe new command `create` is needed?

**Comment by nateprewitt** [comment]
I definitely don't think a new command is warranted because this has been the design since the beginning. The initialization process of pipenv --two/--three is listed in the README under basic concepts as well as being used in the example gif. You'll also see that as the example with pipenv help. We may be able to look at making the usage message more correct though.

**Comment by nateprewitt** [comment]
Ok, so `pipenv --two install` ignores the `--two` option and simply runs ignore and creates a virtualenv with the default `--three` param if none is given. Passing `pipenv install --two` works as expected though, creating a virtualenv with Python 2 before installing.

This means the usage string is definitely incorrect here, but I can't actually find where it's generated. @kennethreitz this looks like a possible issue in `click`, unless you have more insight into something I'm missing here.

**Comment by kennethreitz** [comment]
it's also shown in `pipenv --help`

**Comment by ncoghlan** [comment]
Just noting I also got caught by this, where `pipenv --three install` seemed to work on Fedora, but gave me an environment with Python 2 configured so importing `pathlib` failed.

I switched my setup instructions to `pipenv --three && pipenv install` instead, but there may be scope for a "This probably doesn't do what you want" warning here.

**Comment by nateprewitt** [comment]
Thanks for pinging on this issue @ncoghlan. The usage displayed in `pipenv --help` does appear to still be incorrect, so this issue may have been closed a bit prematurely. I'm unsure if this is a bug in click or how we're using it in Pipenv, but I'm going to open this back up for now while we diagnose.

**Comment by nateprewitt** [comment]
Ok, finally got around to testing this properly. So the issue is how we're using `click` in `pipenv`. When the command `pipenv --three install` is run, it's actually executing two separate commands just like `pipenv --three && pipenv install` would. However, we have a conditional in the base `cli()` function which only executes code if there's no subcommand. This means the `--two/--three` option is silently discarded and then install uses the default of `--three` if the virtualenv doesn't exist.

@kennethreitz, do you recall the reason for only running using options when there's no subcommand? At the very least, I think we need to raise an exception here and inform users there args may not be used as expected in this order.

**Comment by nateprewitt** [comment]
Ok, I've pushed  7b17058 which will now run `--two/--three` regardless of a subcommand being passed. This functions more inline with what people seem to be expecting. The implementation is weird, but I can't find a cleaner way to do with with click.

Feel free to try it out on master, and we'll plan on moving forward with this in the 3.6.0 release.
