### ISSUE TITLE
pip install <> --pre support

### ISSUE THREAD

**Issue by SergeyPirogov** [kennethreitz/pipenv#251]
pip support installation a pre release version of package. 
example i have package in pypi with version 1.0.0a8, I can install it

pip install --pre

How can I do the same with pipenv?

**Comment by nateprewitt** [comment]
Hey @SergeyPirogov, you should be able to install any release of a package on pypi with `packagename==1.0.0a8`. If this does not work (which it may not, we haven't seen anyone explicitly using pre-releases yet) could you please provide an example package where you're encountering this issue? Thanks!

**Comment by SergeyPirogov** [comment]
https://pypi.python.org/pypi/selene

Yes I can install package using pyenv install selene=1.0.0a10 but it was usefull with pip to install pre release versions using --pre, because I don't need to google it in pypi

**Comment by nateprewitt** [comment]
Hmm, so without specifying a specific version, pipenv will install the latest stable release and store the entry in the Pipfile as `package = '*'`. The `--pre` command has the requirement that we'll actually need to determine the version number of the package `pip` chooses and store that in the Pipfile. This would result in an entry like `selene = '==1.0.0a10'` which means it's pinned rather than fluid.

I don't think it's entirely unreasonable to support this, but it is an extension to the API options for install. pip provides several other options that may be useful in edge cases but will create significant clutter. This is a decision more in the purview of @kennethreitz, but my gut feeling is this probably won't be supported in the near future.

In the meantime, you can accomplish this inside pipenv with two commands but without Google.

`pipenv run pip install --pre packge`
Copy the installed version number from the output (e.g. 1.0.0a10).
`pipenv install package==1.0.0a10`

This will get things installed and in your Pipfile. This is obviously not great, but will work for the time being.

**Comment by SergeyPirogov** [comment]
Yeah, there are some workarounds. Thank you
