### ISSUE TITLE
make --ignore-hashes automatic

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#275]
when no hashes are present

**Comment by nateprewitt** [comment]
So I thought about this when we were implementing --no-hashes, and while this is definitely more convenient, it defeats the point of the hashes. --no-hashes in general is a bit weird with us having --require-hashes on every install command.

Hashes become opt-in rather than opt-out at that poin, which I'm not saying is the wrong approach, but they will become prone to silent failure.

If we go this route, we just need to make sure we a big note that this feature is now opt-in when receiving Pipfile.lock files from third parties.

**Comment by jacebrowning** [comment]
Could hashes be enabled/disabled by a setting in the Pipfile?

**Comment by nateprewitt** [comment]
It could but I don't think that addresses the issue. If the hashes are present in the file that's going to lead people to believe it's using hashes unless they specifically instruct pipenv not to. I agree that no hashes in the file would suggest we aren't checking hashes but that's also something we shouldn't expect people to have to check on every project they install.

Honestly, I think I'm OK with opt-in for hashes because they've been more of a struggle than the value they've provided (in my experience). That way when the user knows they're deploying in an environment where they don't want to worry about tampering, they specify --require-hashes in the build, just like pip.

**Comment by kennethreitz** [comment]
I like the current functionality, i just think we should automatically enable `--ignore-hashes` if no hashes are present.

**Comment by kennethreitz** [comment]
done!
