### ISSUE TITLE
"pipenv run" and CWD?

### ISSUE THREAD

**Issue by c17r** [kennethreitz/pipenv#276]
Looks like `pipenv run` explicitly looks for items in venv's bin directory.  Is there a way get it to run scripts that are in the current working directory in a performant manner?

For instance, a django project's `manage.py` file.  The only way I could get it to work in that particular instance is `pipenv run python manage.py` which works but takes 2-3 times longer than just `./manage.py` from inside the venv.  I realize I could `pipenv shell` first which is pretty much what I did pre-pipenv, but I was just seeing if between pipenv and makefiles you could stop worrying about the venv altogether.

something like
```
init:
	pip install pipenv
	pipenv lock
	pipenv install --dev
	pipenv run ./manage.py migrate

serve:
	pipenv run ./manage.py runserver

test:
	pipenv run py.test -v    
```

**Comment by nateprewitt** [comment]
Hey @c17r, `pipenv run` will always be *slightly* slower than calling a script directly because it has to validate the Pipfile and virtualenv before running the command. This does add a little less than a second of overhead, so it will seem magnified on a quick running script like manage.py.

You can try using something like `pipenv shell -c "./manage.py migrate; exit ?$"` which will setup and tear down the virtualenv for the single command. That's the only advice I can give for trying to expedite this situation at the moment.

**Comment by jacebrowning** [comment]
I think you mean `$?` instead of `?$`.

**Comment by c17r** [comment]
He did, which A) takes even longer than `pipenv run python manage.py` and B) I think the `$?` gets the error code from the shell command because I can see what actually gets run is `./manage.py migrate; exit 2`

For now I guess I'll stick with activating the venv.
