### ISSUE TITLE
Executable not installing to bin

### ISSUE THREAD

**Issue by frankV** [kennethreitz/pipenv#285]
I realize this could be a very isolated case as no one else on my team has encountered it, but nevertheless I'm curious if someone else has seen an issue installing pipenv where the executable does not get placed in `Python/2.7/bin/`?

I'm running macOS Sierra 10.12.3 and Python 2.7.10

**Comment by nateprewitt** [comment]
Hey @frankV, to clarify, pipenv isn't being installed in `Python/2.7/bin/`? Are you installing with `pip` and have you tried installing other packages that you haven't used before with that pip command?

Could you tell me what the shebang in `$ which pip` is? Also are you using anything like `pyenv` or `virtualenvwrapper`?

Thanks!

**Comment by frankV** [comment]
I used pip to install and am convinced it's an error with my Python environment on this mac. Note that I have not installed with sudo and even tried the `--user` option for pip - same result.

```
$ which pip
/Library/Frameworks/Python.framework/Versions/2.7/bin/pip
```

I am not installing this in a `virtualenv` since I want it available globally, but do use `virtualenvwrapper` on this machine.

**Comment by nateprewitt** [comment]
So I agree this is likely a local configuration issue. `virtualenvwrapper` has a habit of injecting itself first in the python path which has caused issues for us in the past, but is usually when trying to use pipenv inside of a virtualenv.

`/Library/Frameworks/Python.framework/Versions/2.7/bin/pip` should have a shebang at the top of the script which tells you which python it's using. I'm assuming it's either `/Library/Frameworks/Python.framework/Versions/2.7/bin/python` or `/usr/bin/python`.  I would try installing something odd, like `requests==1.2.3`, with `pip` and verifying it installed where you expected. If it doesn't this is definitely a byproduct of your local environment.

**Comment by frankV** [comment]
Sorry, I misunderstood, the shebang was:
`#!/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`

**Comment by nateprewitt** [comment]
Ok, it looks like `pip` is possibly using a different python executable then. It's likely somewhere in the `/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app` path that the `pipenv` executable is being installed. If that's not being added to your `PYTHONPATH`, then `pipenv` won't work as expected. I'd also verify your `$ python` executable is bound to `#!/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`, and not `/Library/Frameworks/Python.framework/Versions/2.7/bin/python` or some other path.

Since this isn't directly related to Pipenv, I'm going to close this out for now. Please let us know if you find any further issues directly related to the Pipenv project. Thanks for taking the document this in an issue, and feel free to leave additional notes when you solve things.
