### ISSUE TITLE
Install from Lockfile

### ISSUE THREAD

**Issue by isaacsanders** [kennethreitz/pipenv#293]
Hey all,

I am working on deploying an app that is managing its dependencies with pipenv, and I was wondering if there was a way to install directly from the lockfile, as opposed to the lockfile being checked against and updated to match the pipfile at every `pipenv install`.

**Comment by nateprewitt** [comment]
Hey again @isaacsanders :) I don't know if we have a way to force install from Pipfile.lock right now. It will always try to find a difference between the Pipfile and Pipfile.lock before installing. I do agree there are cases when you'd possibly want to skip this part and install directly from the lockfile. I think we can look into that, but I'd like to get @kennethreitz's thoughts here first.

**Comment by kennethreitz** [comment]
hmm, and `--ignore-pipfile` option would be nice.

**Comment by isaacsanders** [comment]
:D

**Comment by nateprewitt** [comment]
Great! Alright @isaacsanders, if you'd like to put together a pull request that hands a `--ignore-pipfile` option from `def install(...)` to `def do_init(...)` and skip over [this conditional](https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L542) when `ignore_pipfile` is passed. Otherwise, I'll toss this together later this afternoon.

**Comment by isaacsanders** [comment]
Have you already gotten started? If not I can do it.

**Comment by nateprewitt** [comment]
Go for it 😊

**Comment by nateprewitt** [comment]
Resolved in #294
