### ISSUE TITLE
Pipenv cannot install packages, suggested workaround doesn't work either

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [kennethreitz/pipenv#318]
I have a simple little project with three dependencies: Flask, Flask-Cors and requests. My Pipfile lists the version for each as "*", since I want to stay up to date and just use the newest version anyway.

When I run pipenv install, I get the following error:

    Could not find a version that satisfies the requirement Flask 
    (from -r /tmp/requirements.txt (line 3)) (from versions: )
    No matching distribution found for Flask (from -r /tmp/requirements.txt (line 3))

along with the suggestion to use ```--ignore-hashes``` to get around this.
However, using the option gives the exact same behavior.

This happens on Ubuntu 16.10, Xubuntu 16.04, and Manjaro Linux.

**Comment by nateprewitt** [comment]
Hey @MyrionPhoenixmoon, thanks for opening this issue. Could you please provide the exact contents of the Pipfile you're using, the value returned from `pipenv --version`, and `pipenv lock -r`?

Thanks!

**Comment by Benjamin-Dobell** [comment]
@MyrionPhoenixmoon I ran into something very similar myself when simply trying specify an _exact_ version. It would seem that `pipenv` currently only supports a very limited subset of the `Pipfile` specification regarding dependency version handling.

I believe the following are not supported:

* Any version ("*")
* Exact version ("0.12")
* Semversion ("^0.12.0)

For your particular use case you should be able to work around this with something like:

```
[packages]
Flask = '>=0.12'
```

**Comment by MyrionPhoenixmoon** [comment]
Thank you, @Benjamin-Dobell, I *just* found that workaround too :)

@nateprewitt 
Pipenv version is 3.5.6 
Output of pipenv lock -r is
```
Fixing package names in Pipfile...
Fixing package names in Pipfile...
Flask
Flask-Cors
nose2
requests
```

Though I suspect that is rather less interesting, now that I manually installed all the dependencies already... Do you need it from a fresh env?

**Comment by nateprewitt** [comment]
@Benjamin-Dobell the first two cases are definitely supported. We may need to look into getting a PR put into the `Pipfile` project further detailing this.

These should all work with the semantics of pip.

```
Flask = '*'
Flask = '==0.12'
Flask = '>=0.12'
```

As for the last one, I can't find an example of the version number starting with a carrot. Could you point me towards something referencing that?

**Comment by nateprewitt** [comment]
@MyrionPhoenixmoon Thanks for getting me that info. It looks like we will need things run in a fresh environment, because there aren't any issues in the info you provided as far as I can tell.

I also need that `Pipfile` too if possible. My hunch is there's a syntax issue of some kind there.

**Comment by MyrionPhoenixmoon** [comment]
`
pipenv install

Fixing package names in Pipfile...
No package provided, installing all dependencies.
Fixing package names in Pipfile...
Pipfile found at /home/myrion/test/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock!
Installing dependencies from Pipfile.lock...
An error occured[sic ;)] while installing!
Could not find a version that satisfies the requirement Flask (from -r /tmp/tmpgo01mv6q-requirements.txt (line 1)) (from versions: )
No matching distribution found for Flask (from -r /tmp/tmpgo01mv6q-requirements.txt (line 1)

You can supply the --ignore-hashes option to 'pipenv install' to bypass this feature.
`

The Pipfile looks like this:
`
[[source]]
url = "https://pypi.org/"
verify_ssl = true

[packages]
requests = "*"
nose2 = "*"
Flask = "*"
Flask-Cors = "*"
`

Pipenv lock -r generates the same output as before.

**Comment by nateprewitt** [comment]
Ok so there's the problem. `https://pypi.org/` isn't a valid endpoint. You'll need to replace that with `https://pypi.org/simple` to fix your issue. Thanks @MyrionPhoenixmoon, let me know if you have any further issues.

**Comment by MyrionPhoenixmoon** [comment]
Huh. Thanks!

I have two follow-up questions, though:
Is there a way to improve that error message? I mean, it was entirely unrelated to the actual error and the suggested workaround didn't help in the least.

Why did specifying versions like ">=2.5" work, then? Shouldn't that also be broken?

**Comment by nateprewitt** [comment]
@MyrionPhoenixmoon that error message is being produced directly from Pip and is related. The endpoint you chose doesn't have a version of the package you specified (because it's not a valid endpoint). There's not really a great way to determine if the user provided bad data, or if the package legitimately doesn't exist. I'm open to suggestions though if you have a clean way to handle this.

Could you provide a little more context on what command syntax you used and how you ran the command for your ">=2.5" case? It should in theory also be broken unless you didn't supply an endpoint. In that case we choose the default `https://pypi.python.org/simple` endpoint.

**Comment by Benjamin-Dobell** [comment]
@nateprewitt My apologies, I'm not sure where I read semver (carret) was supposed to be supported, but it mustn't have been official because I can't find it.

With respect to the other two, the issue is the way the dependency string is concatenated:

https://github.com/kennethreitz/pipenv/blob/0aeaefb914e7fb04b0f8569435c26b7bf27b660b/pipenv/utils.py#L122

One expects to be able to write:

```
[packages]
somepackage = "0.12"
```

_not_:

```
[packages]
somepackage = "==0.12"
```

The latter is very confusing and doesn't match the way `python_version` is set in the very same `Pipfile`.

In the former case you end with a `requirements.txt` of:

```
somepackage0.12
```

which does not exist. Instead we _want_:

```
somepackage==0.12
```

I didn't actually try `*`, however after just a cursory look at the concatenation I thought you'd end up with `somepackage*`, where as you want `somepackage=*`.

**Comment by nateprewitt** [comment]
@Benjamin-Dobell I kind of get where you're coming from, but the examples you're providing seem contradictory. Why is `==12.0` odd but `>=12.0` acceptable? They're both providing a degree of specificity and are inline with how pip itself works. As you noted, `pip` will only function with the syntax `somepackage==0.12` so that's how we're storing it (key = value).

As for `*`, specifying just the package name `somepackage` is equivalent to a wildcard version. The syntax we store in `Pipfile` is `somepackage = "*"` which will result in `somepackage` when installing with `Pip`.

All of these design choices are ultimately a decision of the [Pipfile](https://github.com/pypa/pipfile) project though. `Pipfile` is technically autonomous from `Pipenv`, and I think this was pretty thoroughly discussed before implementation. I would suggest reading through some of the tickets there and opening one of your own if you don't find suitable answers. I'd prefer we move this discussion there rather than continue here since this is derailing the topic at hand. Thanks!

**Comment by MyrionPhoenixmoon** [comment]
@nateprewitt for the ">=2.5" I manually amended the Pipfile, but on testing, that doesn't work, so I must've gotten things mixed up.

As for the error message: I was misled due to the suggestion of "--ignore-hashes", because to me, that means it had a hash mismatch, so it *did* find something but considered it to be the wrong thing. So for me, it would've been sufficient to have the error be "check your source url or do the hash thing", just to indicate that it *might* be wrong. Because you're right, it would be hard to figure out that I entered garbage.

**Comment by nateprewitt** [comment]
The hash thing was definitely a faux pas on our part. I've pushed db4a181 to address this so we're not leading people astray with erroneous error messages. That's probably the best we can do at this point. Hopefully this issue will help anyone else hitting this issue. Thanks for your time working through this :)

**Comment by MyrionPhoenixmoon** [comment]
Thank you for your effort!

I sure hope others will benefit too. It was a weird and frustrating error for me^^
