### ISSUE TITLE
Actually support other indexes. 

### ISSUE THREAD

**Issue by bobcyw** [kennethreitz/pipenv#34]
In some place using pip's download speed is quite slow. So passing a mirror address to pip is very important.

**Comment by cetanu** [comment]
I might be wrong, but you can specify the url in the Pipfile:

    [[source]]
    url = "https://pypi.org/"
    verify_ssl = true

**Comment by kennethreitz** [comment]
That feature currently isn't supported, actually. We need to get it working.

**Comment by kennethreitz** [comment]
Added something to the README for now

**Comment by jpadilla** [comment]
Should we just forward all of these?

```
Package Index Options (including deprecated options):
  -i, --index-url <url>       Base URL of Python Package Index (default https://pypi.python.org/simple). This should point to a repository
                              compliant with PEP 503 (the simple repository API) or a local directory laid out in the same format.
  --extra-index-url <url>     Extra URLs of package indexes to use in addition to --index-url. Should follow the same rules as --index-
                              url.
  --no-index                  Ignore package index (only looking at --find-links URLs instead).
  -f, --find-links <url>      If a url or path to an html file, then parse for links to archives. If a local path or file:// url that's a
                              directory, then look for archives in the directory listing.
  --process-dependency-links  Enable the processing of dependency links.
```

**Comment by kennethreitz** [comment]
Let's just start with `-i` and assume it's always present in the `Pipfile`.

**Comment by kennethreitz** [comment]
done!

**Comment by arruda** [comment]
@kennethreitz  @jpadilla Sorry for disturbing an already closed issue, but it's unclear for me what's the proposed solution.
I imagined that one could use a Pipfile like:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[[source]]
url = "https://my.private.pypi/simple"
verify_ssl = true
```
for example, and instead of treating `project.source` as a single source, would use instead an `project.sources` and do a re-try(if the given package can't be found in the first check for example) for each source whenever had to use this sources (`pip_install` or `proper_case` and others).

I'm think this would be more like a `--extra-index-url` solution, but would also encompass the `--index-url`
