### ISSUE TITLE
can't create pipenv in root directory

### ISSUE THREAD

**Issue by cdetrio** [kennethreitz/pipenv#353]
Trying to create a pipenv in the root directory (`cd /; pipenv --two`) results in an error:

```
Creating a Pipfile for this project...
Creating a virtualenv for this project...
usage: pew [-h] [-p PYTHON] [-i PACKAGES] [-r REQUIREMENTS] [-d] [-a PROJECT]
           envname
pew: error: too few arguments
```

The problem is probably around this line: https://github.com/kennethreitz/pipenv/blob/0156f1e1b397cd8fcfe23738f49cf0bf6067ec76/pipenv/project.py#L33

**Comment by nateprewitt** [comment]
Hey @cdetrio, thanks for opening this issue. You're right that we're assuming a Pipfile will exist in a directory with a name. We don't have a good way to handle root since there isn't a name to pass.

We could special case `/` but that seems like the less than desirable solution. Just to help me understand the problem space a bit better, could you elaborate on why you're looking to deploy a single project in root?

**Comment by cdetrio** [comment]
Thanks for the response @nateprewitt. The use case is in Docker containers. Of course its easy enough to work around, done here by creating a subdirectory: https://github.com/gsalgado/hive/pull/1/files.

**Comment by nateprewitt** [comment]
I think creating a directory for the project is my suggested course of action here. While we definitely could support this, I feel like it will generally be a stumbling block for users and encourages bad directory habits in general.

I'm open to a PR possibly implementing a warning in this case, but that's probably the only actionable item at this point. Thanks again for taking the time to record this in an issue!
