### ISSUE TITLE
Ctrl+] causes pipenv virtual environment to exit. 

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [kennethreitz/pipenv#391]
Running `pipenv, version 4.1.3`
on Fedora using `GNOME Terminal 3.22.1 Using VTE version 0.46.2 +GNUTLS`
Pressing `Ctrl + ]` after running `pipenv shell` causes the virtual environment to exit. 

This is quite problematic as use of vim's tags inside of the virtual env is quite impossible as `Ctrl + ]` is the default navigator for using tags. 

I am more than happy to provide any additional information that would be helpful.

**Comment by nonylene** [comment]
`Ctrl + ]` seems to be escape character of pexpect. 

>When the user types the escape_character this method will return None. The escape_character will not be transmitted. The default for escape_character is entered as Ctrl - ], the very same as BSD telnet. To prevent escaping, escape_character may be set to None.

http://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.interact

**Comment by nateprewitt** [comment]
@Blue-Dog-Archolite thanks for raising this issue. @nonylene is correct, `^]` is the default escape character for pexpect. I've pushed df909ccf0 which will disable the escape functionality for pexpect because it doesn't provide any real value that isn't accomplished by `^D` or `exit`. This will be included in the next release.
