### ISSUE TITLE
Offline Virtualenv creation?

### ISSUE THREAD

**Issue by rnwolf** [kennethreitz/pipenv#408]
Is it possible to create a virtualenv while offline?

**Comment by nateprewitt** [comment]
Hey @rnwolf, I hadn't tried this before but it seems pipenv doesn't currently allow this. It looks like we can easily make this possible, but before we go down that route, when are you seeing this being useful? Do you already have all of your dependencies downloaded?

**Comment by rnwolf** [comment]
I have a couple of hours commuting time on the train per day. No wifi or fast mobile signal on the train. I might them want to do some experimentation/training and that sometimes involves creating a new virtual environment for that piece of work. The dependencies are usually in the pip cache already, but every new environment setup still requires a call to the internet.

**Comment by nateprewitt** [comment]
Hmm, I spent some time trying to work out why `pipenv` wouldn't work offline, and found that it does in fact seem to work. Shutting off wifi, I'm still able to create a new virtualenv with `pipenv --three`. There is definitely a more significant lag when creating the new virtualenv offline, but it finishes in ~30 seconds. This same latency is seen in running virtualenv by itself though, so this appears unrelated to `pipenv`.

If you're able to produce an indefinite hang, could you please provide the steps?

**Comment by rnwolf** [comment]
Attached is file outlining OFFLINE and ONLINE commands and output.
[pipenv-offline-error.txt](https://github.com/kennethreitz/pipenv/files/1072913/pipenv-offline-error.txt)

**Comment by nateprewitt** [comment]
Hey @rnwolf, thanks for the output file! As you can see in the traceback, your setup is failing inside of the `wheel` module because pip can't reach PyPI. This is code outside of requests and *I believe* will fail with the same command `pew new my_test4-_rT_gPHn -d -p python` outside of pipenv. Could you please confirm that for me? Also while we're here, could you check `virtualenv my_test4-_rT_gPHn` while offline as well?

If neither of those work, you will need to have the basic packages `pip, setuptools, pkg_resources, wheel` installed before the virtualenv can be created. I'm not sure if there's anything we can do otherwise.

**Comment by nateprewitt** [comment]
@rnwolf, I'm closing this out as won't (can't) fix. There's not a lot we can do if you don't have the minimum required packages downloaded before trying to create a virtualenv offline. This is a failure in virtualenv rather than pip itself, and I don't think we can support a work around for that at this time.

Please feel free to provide any more information if it comes up.
