### ISSUE TITLE
Explicit init command

### ISSUE THREAD

**Issue by rapilabs** [kennethreitz/pipenv#426]
Would be nice to have an explicit command for creating a Pipfile, at the moment I think I discovered that you do it with `pipenv --three` via the animated gif.

**Comment by nateprewitt** [comment]
Hey @rapilabs, the intended workflow is that your Pipfile will be created when you start your project. Any command you run with `pipenv` will create a new Pipfile and virtual environment if one doesn't already exist for the project.

If you're starting a new project, `pipenv --three`, `pipenv --two`, or `pipenv --python python-x.x` are the commands you would use. These are documented in multiple places in the README and on the home page of the documentation website, pipenv.org.

I'm not sure I see a point in having a command that only creates the Pipfile. This is primarily because it's an additional step most people will find cumbersome, and you can't do anything with the Pipfile until the virtualenv is initialized anyway. For that reason, I'm going to close this out, but please let us know if you have any further feedback or thoughts. Thanks!
