### ISSUE TITLE
Configure --trusted-host 

### ISSUE THREAD

**Issue by mirosval** [kennethreitz/pipenv#428]
Pip has a cli setting `--trusted-host` that allows you to use a private package index over http (as opposed to https).

Pipenv does not allow setting of this field and so it is not possible to use the custom package index.

I imagine this could be fixed by adding the setting to pipfile under the `[[source]]` section, or by automatically extracting the host from the source url.

```
The repository located at <private_url> is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host <private_host>'.
```

**Comment by nateprewitt** [comment]
Hey @mirosval, expanding the Pipfile spec to handle specifying this kind of information should actually be raised against the [pypa/pipfile](https://github.com/pypa/pipfile) repository. I don't think this is a feature we intend to explicitly support in Pipenv at this time, but pip provides the tools you need to handle this scenario.

If you have a known set of indexes you wish to only use http on, you can specify a `trusted-host` list in your `pip.conf` file, and Pipenv should respect those. That said, I would HIGHLY suggest pushing your indexes to use HTTPS. Allowing things like software packages to be transferred in clear text leaves ample opportunity for your code to be tampered with before install. Even on a what you may think is a "secure" network.

I'm going to close this out since it has a workable solution currently. Please, let us know if you have any related questions or comments though. Thanks!

**Comment by mirosval** [comment]
@nateprewitt Thank you, I fully agree with the https approach, I managed to get that done in the end too.
