### ISSUE TITLE
Automatically install dependencies when creating a new environment

### ISSUE THREAD

**Issue by randomPoison** [kennethreitz/pipenv#429]
I'm using pipenv for a new project in the hopes that it'll help simplify the on-boarding process for new devs. Already it's much better than teaching people how to use virtualenv. Ideally, I'd like new contributors to be able to simply clone the repo, then run e.g. `pipenv run app.py` to run the code locally.

The biggest blocker of that right now is that you have to manually run `pipenv install` once before you can do `pipenv run python app.py`. I think pipenv should automatically install all dependencies when creating a new environment if there's already a `Pipfile` present. This would allow you to run `pipenv run python app.py` immediately after cloning a project and it'll "just work".

If the maintainers of pipenv agree that this feature is desirable, I'd be happy to submit a PR adding the functionality.

**Comment by jacebrowning** [comment]
Would it also reinstall dependencies if `Pipfile` changes between runs?

**Comment by nateprewitt** [comment]
Hey @excaliburHisSheath, thanks for proposing this idea! I'm glad you're finding some good uses for Pipenv.

I appreciate wanting the simplicity of one command, but I think this introduces some unexpected issues/complexities. How does `pipenv run` function in the case where you aren't creating a new repository? What do you do if the `Pipfile.lock` and `Pipfile` differ? Are we reinstalling everything each time? What if you need `dev-packages` in some cases but not in others? 

Most of these cases mean reimplementing a lot of the `pipenv install` functionality in `pipenv run` too. We'd likely need to introduce a flag to `run` in order to toggle this too, but that's extra API surface area I'm not excited about. Especially since this can be solved relatively simply. Creating a bash script similar to what's below should accomplish one command functionality without overloading command options.

```bash
pipenv install --python pythonX.X  # Initialize app and install dependencies
pipenv run python app.py
```

Would something like that be suitable for your requirements? Please let us know if you have any thoughts on what I'm seeing as downsides, or you think I'm missing anything. Thanks again for the proposal!

**Comment by excaliburHisSheath** [comment]
@nateprewitt Thanks for the quick response! I have an idea of how I'd want the feature to work with regards to the points you've brought up.

As a starting point, I'd like `pipenv run ...` to behave almost exactly the same as running `pipenv install && pipenv run ...`, effectively creating the environment if it doesn't exist, installing dependencies if they're not already installed, then running the command within the environment. Functionally, that would do what I want, though in practice `pipenv install` is too slow a process to run every time I want to use the env; Even when all dependencies are installed and up-to-date, `pipenv install` takes multiple seconds to run in a project with only 2 direct dependencies.

Ideally, I'd want to replace most usage of `pipenv install` in favor of a `pipenv run` that does the following:

* If no virtualenv exists for the project, create one.
* For each dependency in `Pipfile.lock` that isn't installed in the environment, install the dependency. This should include generating a `Pipfile.lock` from the `Pipfile` if one doesn't already exist, akin to the way `pipenv install` currently behaves.
* If the `Pipfile` has changed since last running, update the `Pipfile.lock` with any changes in dependencies, then update an installed dependencies in the environment to match the lock file. (@jacebrowning does that answer your question?)
* If there are no changes to the `Pipefile` and all dependencies are already installed, then the install/update phase should be a no-op. It should quickly double-check that the right dependencies are installed, but otherwise it shouldn't re-install any dependencies or do anything to re-initialize the environment.
* Once installation and update is done, it should run the command within the environment, same as `pipenv run` does now.

The idea here is that `pipenv run` is the only command you need 90% of the time. You don't need to manually run `pipenv install` because `pipenv run` will setup your environment and update any dependencies each time you run. I don't know if this implementation is feasible with how dependencies are installed, or if it's even something that would appeal to most python developers, but for me it would be pretty close to an "ideal" workflow.

To give some background, I'm used to using [Rust](https://www.rust-lang.org/) and its package manager [Cargo](http://doc.crates.io/). With Cargo, you simply do `cargo run` within a Rust project and it will download dependencies, compile them, compile your project, and then run it. Now that I'm doing some Python development, I've been looking for a tool that can give me a development experience as smooth as what Cargo provides. pipenv has made the Python development experience much nicer, but there are still some pain points. Having `pipenv run` handle more of the setup automatically would smooth things out a bit more.

With regards to the shell script you suggested, I don't think it's necessary. Assuming that this feature doesn't make it into pipenv, manually running `pipenv install` is fine by me :)

**Comment by nateprewitt** [comment]
Thanks for such a detailed breakdown of what you're looking for @excaliburHisSheath :) So, I think I can get onboard with this, but we'll need to find a way to avoid any noticeable slowdown on your average `pipenv run`. I'll put this on the list of things to look at for the next minor release.

**Comment by excaliburHisSheath** [comment]
@nateprewitt Excellent! I'm glad the request isn't unreasonable :) If this is something I can help implement, I'd be happy to do so. Otherwise let me know if there's any other way for me to help out.

**Comment by kennethreitz** [comment]
I think we're going to leave things as they are, for now.
