### ISSUE TITLE
pipsi installation does not work out of the box

### ISSUE THREAD

**Issue by anlutro** [kennethreitz/pipenv#432]
After doing `pipsi install pipenv`, it does not work, because the `pew` bin file does not get installed by pipsi.

This is solved by symlinking it yourself after installing:

```
ln -sf ~/.local/venvs/pipenv/bin/pew ~/.local/bin/
```

This may be an issue with pipsi, not pipenv.

**Comment by nateprewitt** [comment]
Thanks for reporting this, @anlutro. This has been an issue with `pipsi` since Pipenv started vendoring dependencies. We should likely either modify the documentation so the user knows they'll need to install pew separately, or remove the suggestion to install Pipenv with `pipsi` entirely. I'm in favor of the latter because I don't see much utility in this use case, but I'd like @kennethreitz to sign off on that.

**Comment by kennethreitz** [comment]
Our directions clearly outline the fix for this.

**Comment by nateprewitt** [comment]
You're right, sorry for the ping. I'm closing this out as resolved since it's already in the documentation and there's no actionable steps for adjusting the process.

**Comment by kennethreitz** [comment]
Never apologize for pinging me :)

**Comment by uranusjr** [comment]
Would it be a good idea to include a paragraph in the docs explaining *why* pew needs to be installed separately? It confused me a little in the beginning, being familiar with pip handling all the dependencies for me, until I dug into how pipsi works and how pipenv uses pew. I can open a pull request if you think this is a good idea.
