### ISSUE TITLE
Support environment variables in some way

### ISSUE THREAD

**Issue by nkantar** [kennethreitz/pipenv#441]
This may be out of scope for Pipenv, but here it goes anyway: It may be worthwhile to support dealing with environment variables in some way.

(All the issues I found mentioning environment variables didn't seem to talk about this specific scenario.)

## The Problem

A simple example is the recommended way of running Flask (from [Flask docs](http://flask.pocoo.org)):

```sh
$ FLASK_APP=hello.py flask run
```

With Pipenv this would have to be:

```sh
$ pipenv run FLASK_APP=hello.py flask run
```

This is all simple enough. But what if you're running an application with a few sets of API keys, or something like that? Consider:

```sh
$ pipenv run FLASK_APP=hello.py GITHUB_CLIENT_ID=qiu5gnl1glu54ignwi5gn GITHUB_CLIENT_SECRET=ergiebqkgrybreugyb34t34kuwy flask run
```

And it only gets worse.

## The Solutions

I have two (mutually inexclusive) approaches in mind:

### 1. Heroku-like Interface

An interface inspired by `heroku config` seems like it could work (from [Heroku docs](https://devcenter.heroku.com/articles/config-vars]):

```sh
pipenv set GITHUB_USERNAME=joesmith
Adding config vars
GITHUB_USERNAME: joesmith

$ pipenv env
GITHUB_USERNAME: joesmith
OTHER_VAR:       production

$ pipenv get GITHUB_USERNAME
joesmith

$ pipenv unset GITHUB_USERNAME
Unsetting GITHUB_USERNAME
```

### 2. `.env`-like File

Maybe Pipenv could automatically read a file, akin to Docker's `.env`:

```sh
FLASK_APP=hello.py

GITHUB_USERNAME=joesmith
OTHER_VAR=production
```

## And Then&hellip;

I'd be happy to take a stab at one or both of these if the maintainers would be interested in merging them. Or something else, for that matter.

Alternately, if there's already a good way to solve this problem, I'm all up for some good ol' TIL. :grin:

**Comment by uranusjr** [comment]
`pipenv run` passes all environs to the subprocess, so you can simply do

```
FLASK_APP=hello.py pipenv run flask run
```

**Comment by nateprewitt** [comment]
Hey @nkantar, thanks for taking the time to put together this feature request. We've discussed having a config file of some kind in the past to manage things like environment variables for each project. I'm not completely against that, but there are some gotchas. Last time we discussed it Kenneth wasn't excited about the idea.

I think this is something easily solved with something like a bash script. You only need to init FLASK_APP once and then you should be able to run `pipenv run flask run` freely. I realize this isn't the cleanest approach but it's the best option I think we have available at the moment.

Please let us know if you have any further thoughts. I'm going to close this out for now though since I don't think there's anything we can do at this time.

**Comment by hugobessa** [comment]
Folks, I'm trying to run this: `HELLO='hello' pipenv run echo $HELLO`. And nothing is being printed.

I'm using ubuntu 16.04, pipenv 8.3.2.

Do have any idea why this isn't working?
