### ISSUE TITLE
Windows Support - add appveyor?

### ISSUE THREAD

**Issue by rsyring** [kennethreitz/pipenv#447]
It's not clear from the docs if this project officially supports Windows.  There are old/closed issues that imply no and some PRs that imply yes.

If it is supported, could you include that in the readme?  Also, would you be interested in a PR that adds appveyor support?

**Comment by nateprewitt** [comment]
Hey @rsyring, we support windows in the majority of the 3.X series of pipenv. Kenneth currently maintains a Jenkins server where we do our Windows testing because he wasn't pleased with Appveyors performance. I believe that may have been disabled about a month ago though, so we may need to check in on getting that running again.

In the meantime, the current release of pipenv should be compatible with Windows. Please let us know if you encounter any specific issues. I'll update the documentation later today unless you'd be interested in providing a PR.

**Comment by rsyring** [comment]
Thanks @nateprewitt for the quick response!  I appreciate the clarification and I'm sure the note in the docs will help others who have the same question.

For what it's worth, I have a paid version of AppVeyor that my company maintains for testing Windows support of our OSS and internal customer projects.  As you can see below, the response times on the paid versions are significantly better than what they offer free accounts:

https://ci.appveyor.com/project/level12/keg-6gnlh/build/1.0.89

Would you be interested in having us provide AppVeyor CI for this project from our paid account so it runs faster?

**Comment by nateprewitt** [comment]
Thanks @rsyring! That's an incredibly generous offer, I'm going to page @kennethreitz on making a decision here. He's at Djangocon this week so there may be a delayed response.

Thanks again!

**Comment by kennethreitz** [comment]
We have a sponsored account, thankfully :)

**Comment by KeynesYouDigIt** [comment]
work around for appveyor/powershell/windows I ended up needing for error
`Command executed with exception: Updated Pipfile.lock (780220)!`
```yaml
  - ps: python -Wignore -m pip install pipenv
  - ps: rm Pipfile.lock
  - ps: $PIPENV_QUIET="true"
  - pipenv run conditional_install
```
