### ISSUE TITLE
pipenv shell should respect your current shell.

### ISSUE THREAD

**Issue by jonparrott** [kennethreitz/pipenv#452]
I use Fish shell, but unfortunately running `pipenv shell` spawns a weird, foreign, and confusing bash shell.

It'd be nice if `pipenv shell` spawns my preferred shell. :)

**Comment by nateprewitt** [comment]
Hey @jonparrott, this is because Fish doesn't update the SHELL variable in some cases (I don't know which). We use that to launch the subshell, so yours is likely defaulting back to /bin/bash.

The previously suggested workaround has been to update your profile/bashrc with the correct SHELL variable for Fish. I'm open to other ideas though for a better implementation if you have any 😁

**Comment by jonparrott** [comment]
Ah interesting. I thought that might be what's going on - thanks, I'm gonna close this for now.
