### ISSUE TITLE
xonsh support

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#498]
we apparently don't work well on xonsh, according to @astronouth7303

**Comment by astronouth7303** [comment]
So, as a general rule: venv tools don't work on xonsh, because we have 0 bourne compatibility.

xonsh has its own tool called [vox](http://xon.sh/python_virtual_environments.html) that manages, activates, and deactivates virtual envs in python. By default, it stores venvs in `~/.virtualenvs` and will manage them when called.

I've written `xontrib-avox` that does this automatically based on the current working directory, matching the "project name" to available venvs.

The cool thing is that because avox uses vox, the `vox` command still works, vox-related events still fire, and any additional tools that integrate with vox still work. (At least, in theory. Our userbase is small and I'm not actually aware of any tools in this category. :cry: )

From a loose scan of the features and such, it looks like the only problem is `pipenv shell`, because xonsh is also python, so trying to call xonsh with a venv set is potentially problematic and unfortunately would need to be fixed on our end by redoing how we're packaged and called. (Potentially related to xonsh/xonsh#1861?) Otherwise, because there's no shell sourcing and nothing that needs to be added to rc files, I'm guessing pipenv doesn't do emit any bourne, and otherwise should work fine.

The thing I personaly would like to see is avox-style automatic detection of pipenv projects and doing appropriate activations, but there's an argument to be made for feature parity between shells.

**Comment by astronouth7303** [comment]
@laerus

**Comment by kennethreitz** [comment]
calling this out of scope for now.

**Comment by rca** [comment]
I've been happily using xonsh with `pipenv shell --fancy` for a number of months, and on a fresh install (Mac + homebrew + Python3.7 + pipenv + xonsh).  I stumbled upon this issue after setting up a brand new machine and finding myself with a very broken `pipenv shell`.

It appears the new shell logic in `2018.7.1` doesn't work well with xonsh.  The symptom is that an interactive program, say `vi`, within the `pipenv shell` will immediately background itself.

Downgrading to `pipenv==2018.6.25` fixed the problem for me.

Thank you!

**Comment by rca** [comment]
I had made a pretty big mess the first time around, but am still able to repro with a cleaner install using the python.org 3.6 package.

I will elaborate in an issue under shellingham.

Thank you.
