### ISSUE TITLE
Re-add support for --no-hashes

### ISSUE THREAD

**Issue by cab2753** [kennethreitz/pipenv#524]
It would be nice to be able to run `pipenv lock -r --no-hashes` to generate the contents of requirements.txt without hashes.

It looks like support for this was removed recently. However, it is still a documented feature:
http://docs.pipenv.org/en/latest/advanced.html
> If you wish to produce a Pipfile.lock without hashes, you may also use `pipenv lock --no-hashes`.

This is the output in 6.2.4:
```
$ pipenv lock --no-hashes
Error: no such option: --no-hashes
```

**Comment by kennethreitz** [comment]
I have no intention of disabling hashes again.

**Comment by kennethreitz** [comment]
You can run `pipenv run pip freeze` for the file you want.

**Comment by techalchemy** [comment]
@cab2753 to clarify, the `--no-hashes` option existed because earlier iterations of pipenv required a lot of network overhead to get hashes.  Having this option made sense because it was very slow.  We have addressed that problem so it no longer makes any sense to retain this functionality.  We should remove it from the documentation however

**Comment by kennethreitz** [comment]
Removed.

**Comment by cab2753** [comment]
Makes sense. I think it would be good to replace that part of the documentation with `pipenv run pip freeze`. Although it's very obvious I could have done that, I didn't even think of it!

**Comment by kennethreitz** [comment]
Will consider it!

**Comment by smsearcy** [comment]
I realize this is closed but wanted to make one other observation.  There is a difference between running `pipenv run pip freeze` and `pipenv lock -r --no-hashes` in that the latter includes information about alternate indexes for different packages.  That is significant for me because I have packages that are not from PyPI and thus do not have hashes and need specific URLs.

We also do a editable installation to create the command line entry points via setuptools (very handy when working in predominately Windows).  So to use the generated requirements file requires stripping out all the hashes and it would be very helpful to have the option of generating it without the hashes again.
