### ISSUE TITLE
Nice new colors unusable on white background

### ISSUE THREAD

**Issue by simonpercivall** [kennethreitz/pipenv#545]
The white text color of `pipenv graph` (for instance) isn't really easily readable on white backgrounds; it would be wonderful if it were.

Thanks.

**Comment by kennethreitz** [comment]
Pipenv has a no color mode set `PIPENV_COLORBLIND=1`, 

99% of people use black terminals. and, you can configure those colors, normally.

**Comment by kwbr** [comment]
I am not sure about those 99%

https://opensource.com/life/14/9/what-color-terminal-background

**Comment by kennethreitz** [comment]
those people shouldn't have WHITE configured to be the same color as your background.

Same with black on a black background — it should be off-white and off-black. This is a terminal configuration issue, not a pipenv issue.

**Comment by kennethreitz** [comment]
And, as mentioned, there is a setting to disable colors, if you prefer.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/1f1e9423688ec6c26c7214c21c8eda52f2c81d36

**Comment by kennethreitz** [comment]
Fixed in v7.9.3

**Comment by gvanem** [comment]
Dark blue foreground on a blue background is equally invisible. As  in `pipenv --man`:
![pipenv-man](https://user-images.githubusercontent.com/945271/32992867-68970a44-cd50-11e7-8908-29934f184dd9.png)

Do you see the `run`? (4NT shell on Win-10).
Since I'm a Python neophyte, I had to go into `pipenv/vendor/colorama/ansitowin32.py` to fix this.

**Comment by nateprewitt** [comment]
@gvanem, I'm not sure we can do much here. No matter which colors we choose, you will always be able to set your terminal background to a similar color. Black and white backgrounds account for the majority of terminals and supporting those is probably all we'll be doing at this time.

**Comment by techalchemy** [comment]
However you can change what 'blue' means for your terminal rendering

**Comment by gvanem** [comment]
@techalchemy What's the easiest way? (I've just started with pipenv today. Not so promising so far).

**Comment by erinxocon** [comment]
@gvanem This really depends on your terminal.  On my mac, I use iTerm which gives me the ability to define ansi colors.  This is essentially what themes do.  You can define foreground blue to be different than background blue.

**Comment by erinxocon** [comment]
@nateprewitt I know we don't want to go down a rabbit hole of supporting everything, but on posix the majority are black and white backgrounds, however for windows, powershell is just straight up blue.  It is also not as straightforward to change ansi colors in powershell.  Given that it's the default shell on windows (not including cmd), and not many people use `Cmder`, we should perhaps look into changing that color so it works on posix and windows out of the box.

**Comment by gvanem** [comment]
> change what 'blue' means ..

My response to this really meant, "*what change in **pipenv** can easly do*". I know how to change the colours in Windows console. Duh!

But compared to many other consoles, WinCon is a old dog. I think displaying those cool emojis would require something completely different; Xterm / Cmder for Windows?

**Comment by erinxocon** [comment]
@gvanem Pipenv relies on another package, crayons, to do it's colors.  There isn't much in pipenv to change what blue means unless you change the ansi color it calls in your terminal to something else.  We could avoid using blue, which I am looking into now for windows powershell support out of the box on windows.  I personally use Cmder for windows and it's a lot better at displaying the fancy colors pipenv uses.

**Comment by kennethreitz** [comment]
Who changed the colors?

**Comment by erinxocon** [comment]
@kennethreitz I'm not sure, gotta look through the commit log.  Were the colors different originally for man?  I can't remember.

**Comment by kennethreitz** [comment]
Those parts aren't to be touched by anyone but me.

**Comment by kennethreitz** [comment]
So if they were changed, please revert the changes back to their original
state.

**Comment by Pomax** [comment]
would it be possible to make nocolors a flag, too, so that `pipenv --no-colors run python blah` can be called on case-by-case basis rather than turning it off at the system level? Especially on windows10 I find myself using at least three different command lines (cmd, PS, and bash) and for sanity they're all set to different schemes, only one of which really needs no-color to kick in.

**Comment by kennethreitz** [comment]
@Pomax there is an environment variable you can set. Check the docs ;)

**Comment by Pomax** [comment]
Indeed, that's what I'm currently doing, but it's not exactly convenient. It would just be *much* nicer to also have a `-cb`/`--color-blind` flag, especially as that also makes it possible to do selective color-or-not when it's run as part of a larger build system (for instance, as part of a docker + node + python bootstrap), where an environment variable would be overkill, requiring setting and then unsetting just for a single pipenv run.

**Comment by kennethreitz** [comment]
`PIPENV_COLORBLIND=1 pipenv run python blah

**Comment by kennethreitz** [comment]
effectively identical

**Comment by Pomax** [comment]
100% not possible in windows, hence the _flag request_ because that's presumably little effort to code in, while making every (forced or voluntary) windows dev's life much nicer.

**Comment by uranusjr** [comment]
While I agree (being a Windows user myself) it would be much simpler to have a flag instead of environ if you want the flag/environ to affect only one command, I don’t really understand the usage of this particular case. Why would you only want to disable colours for this particular command? For me personally, the preference in shell, or even system-based, so I would just set the environ in user preferences, or run `set PIPENV_COLORBLIND=1` on shell startup and use the shell without colours.

Note that the environment variable does not affect colours in the shell, only in Pipenv. Or it should, otherwise it’s a bug.

**Comment by Pomax** [comment]
I use cmd and ps, both with blue backgrounds, one with yellow text, one with white text, as main CLI, with several "on the fly" cmd instances that do a thing and then disappear again. Running pipenv will "hijack" the colors, and will not restore them after it's done. For some code runes, that's fine. For others, that's annoying as hell and having to reset the colors manually after every pipenv run is a chore that can easily be fixed with a simple runtime flag so that even different pipenv runs in the same CLI can be told to either allow colors through, or ignore them entirely.

**Comment by uranusjr** [comment]
In that case I think maybe we are solving the wrong problem. It sounds more reasonable to me if Pipenv (actually Crayon, I think) could restore the colours after the command.

**Comment by Pomax** [comment]
I'll be honest: a flag in addition to env var hooking would immediately solve my problem, and open up options for others who are currently stuck with only the environment variable solution, whereas going further and further upstream just keeps the problem unsolved for months while people keep going "we could trivially solve this here and now, for every possible tool that might cause this problem upstream, but let's push for fixes in all of those instead". I've told people that same thing in the past, but ultimately the solution that fixes it "for everything" always wins, I'd rather short-circuit that process and still request that flag here in pipenv, simply because it solves this problem immediately, and for every possible tool (including ones I don't use, and ones that others use who do not have github accounts or even file bugs/fr issues because it's just not a thing they do).

**Comment by uranusjr** [comment]
I’m sure you’re familiar with the saying about something in software being trivial does not mean you should implement it, especially not quickly. Bad design lasts forever, the trivial solution right now can be maintenance headache for the rest of your life. Well, maybe not yours, but certainly mine (and all Pipenv maintainers). Please understand the maintainers’ hesitance to implement a change, especially in the user interface. The effect lasts long.
