### ISSUE TITLE
Add support for setup.py files

### ISSUE THREAD

**Issue by Colin-b** [kennethreitz/pipenv#592]
Hi,

Is it possible (or planned) for pipenv install command to check for setup.py file?

In order to extract dependencies from install_requires (and other extras_require sections).

Thanks and Regards

**Comment by techalchemy** [comment]
Duplicate of #508 and #512

**Comment by kennethreitz** [comment]
unfortunately, pip-tools does not support this feature.

**Comment by kennethreitz** [comment]
If this issue is solved, we can tackle this: https://github.com/pypa/setuptools/issues/1153

**Comment by kennethreitz** [comment]
e.g. currently, `setup.py --requires` does not work.

**Comment by kennethreitz** [comment]
got this working! will be in v7.3.0

**Comment by kennethreitz** [comment]
released

**Comment by sschuberth** [comment]
So, does this mean `pipenv` should be able to import from `setup.py` in a similar way it does [from requirements.txt](http://docs.pipenv.org/en/latest/advanced.html#importing-from-requirements-txt)? I'm asking because I cannot get it to work in pipenv 7.3.7. E.g. when cloning https://github.com/nexB/scancode-toolkit and running `pipenv install`, the generated `Pipfile` is almost empty, whereas I would have expected it to contain the `install_requires` dependencies from `setup.py`.

**Comment by kennethreitz** [comment]
no, that will not work

**Comment by kennethreitz** [comment]
`pipenv install -e .`

**Comment by sschuberth** [comment]
Please bear with me (I only occasionally do Python), but how do I know I need the `-e` in this case?

**Comment by kennethreitz** [comment]
you want to install the current directory as editable.

**Comment by sschuberth** [comment]
I know that the `-e` stands for "editable", but I would not have guessed that it's required, because I actually don't want to necessarily edit anything.

**Comment by kennethreitz** [comment]
you want the current directory's changes to be reflected...

**Comment by kennethreitz** [comment]
otherwise it will just be a snapshot of the current directory.
