### ISSUE TITLE
git - Should Pipfile.lock be committed to version control?

### ISSUE THREAD

**Issue by LeCoupa** [kennethreitz/pipenv#598]
When two developers are working on a projet with different operating systems, the `Pipfile.lock` is different (especially the part inside `host-environment-markers`).

[For Composer, most people recommend to commit `composer.lock`](https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control). Do we have to do the same for Pipenv?

**Comment by kennethreitz** [comment]
i recommend it.

**Comment by kennethreitz** [comment]
Especially for applications. For libraries, less so.

**Comment by LeCoupa** [comment]
Thanks a lot @kennethreitz

**Comment by salty-horse** [comment]
Should this recommendation be documented? Perhaps in a section similar to [Composer's](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control).

**Comment by dougireton** [comment]
Are their negative consequences to using a Pipfile.lock across OS types? In other words, if I generate my Pipfile.lock on MacOS, then deploy to Linux will Pipenv "do bad things"?

**Comment by uranusjr** [comment]
@dougireton This depends on your dependencies. Using a lockfile from a different OS is fine if all your packages are modern and well-behaved (either platform-agnostic or have good cross-platform support). Otherwise Pipenv can do things wrong, like installing dependencies that don’t work, or not installing all needed dependencies.

**Comment by kennethreitz** [comment]
Generally, yes you should commit it to version control.

**Comment by behrangsa** [comment]
How come pipenv's own `Pipefile.lock` is not added to git then?

**Comment by kennethreitz** [comment]
because we are special snowflakes.

**Comment by anentropic** [comment]
I'm happy to take this advice as correct but I would like to understand why it is given.

the docs say:
> Generally, keep both Pipfile and Pipfile.lock in version control.

but I couldn't find any more reasoning in the docs, can you point me to it?

Pipfile.lock is auto-generated and contents will differ depending on platform. If I'm developing on macOS and deploying to Debian ...already it sounds to me like I don't want the lock file in version control.

Then the comment above says:
> Using a lockfile from a different OS is fine if all your packages are modern and well-behaved (either platform-agnostic or have good cross-platform support). Otherwise Pipenv can do things wrong, like installing dependencies that don’t work, or not installing all needed dependencies.

Again it sounds like I would not want the lock file in version control.

Here is someone asking similar question https://github.com/pypa/pipenv/issues/954

Reading through the responses on that issue I have a clearer idea of why I would want it. I think the docs need more elaboration.

The related question is how explicitly should versions be specified in the Pipfile?

If I do `pipenv install <package>` during development to get the latest version, it will go in the `Pipfile` with no version specifier. If everyone else gets my `Pipfile.lock` from vc and does `pipenv install --ignore-pipfile` then get pinned to the versions I installed, and no need to be more specific in the Pipfile. Later I can `pipenv update <package>` and the Pipfile won't change but the lock file will.   Is this the intended workflow?

And I would only add version specifier to `Pipfile` if for example I knew at dev time that I needed to install a non-latest version?

Also I noticed in the example Dockerfile you use `pipenv install --deploy` rather than `pipenv install --ignore-pipfile` ...they seem to have similar meaning, I would like to understand the subtlety of one vs the other.

(loving pipenv so far though!)

**Comment by anentropic** [comment]
I just found some more opinion from the pipenv tool itself:

```
requirements.txt found, instead of Pipfile! Converting…
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did.
We recommend updating your Pipfile to specify the "*" version, instead.
```

**Comment by uranusjr** [comment]
This thread is quite old, but since it emerges again I guess it is best to make a definite, up-to-date statement. As of March 2018, the answer to this question is yes, you should always commit the lock file. Always.

**Comment by mmohaveri** [comment]
@uranusjr could you please explain why?

what has changed in March 2018 that changed the answer from "generally yes" to "always yes"?

What about the issue you explain earlier, is it fixed?

>  Using a lockfile from a different OS is fine if all your packages are modern and well-behaved (either platform-agnostic or have good cross-platform support). Otherwise Pipenv can do things wrong, like installing dependencies that don’t work, or not installing all needed dependencies.

**Comment by techalchemy** [comment]
Nothing is different. You should commit it to version control.  If there are os-specific markers they should be included automatically.  Because `setup.py` files are non-deterministic, it _is possible_ to resolve a package on linux and find that it resolves differently on windows, but there is nothing we or anyone else besides the package maintainer can do about that.  You won't know that's a problem unless you encounter it.  If and when you do, simply re-lock and see the diff.

**Comment by gsemet** [comment]
For application using pipenv, yes you track the lock files.

My librairies however I write using pipenv (and use PBR to reflect to setup.py and an automatic generation of requirements.txt so PBR is happy once the package is deployed), I do not track the lock file. Pretty simple

**Comment by kuwv** [comment]
Old conversion but IMO lock files should definitely be added. What I feel is missing from this is how they should be handled with gitattributes.

Either ``` Pipfile.lock -diff ``` or ``` Pipfile.lock linguist-generated ``` seems correct.

**Comment by jerome-diver** [comment]
I misunderstand and there is a lake of clarity about:

1. what if Pipenv.lock is ignored (not tracked) ? 

1. what if Pipenv.lock is tracked ?

1. Do we have to track lock file and WHY (and WHEN is not always) ?

I consider that doesn't answer "why" do that means that people do without know why. That is a terrible way to do things in the life.

Said "you should always do this" definitely doesn't explain anything and then doesn't teach nothing about the supposed "best practice". It is not a way to know something to just accept without know, and then if you can not explain why exactly and what can be the difference between do it or not, it is because you do it without really  know why. That can be considered as a sectarian practice to do things without understand why, and next, to tell people they have to do this without be able to understand and explain why.

I appreciate also some other developers share there own experiences (good point there), but it doesn't clarify the final subject.

Please, question is very clear, but for me, answer is not (i maybe miss something around). There is something to do there maybe to help me to target the official explication about why to track a lock pipenv file ?

Thank you

**Comment by gsemet** [comment]
I commit Pipfile.lock in every of my Python projects. It ensure the reproductibility of the build. For application and also for library. It enusres there is not "resolve" execution launched in my CI pipeline, to avoid at much as possible break if someone push a newer version of one of my dependencies on Pypi.

**Comment by jerome-diver** [comment]
@gsemet but when i open Pipefile, i can see there is versioning ablility on each library, and also the server link origin. What else different in the lock file around this target versionning libs subject then ?

**Comment by fridex** [comment]
> @gsemet but when i open Pipefile, i can see there is versioning ablility on each library, and also the server link origin. What else different in the lock file around this target versionning libs subject then ?

Pipfile states just direct dependencies. Pipfile.lock states fully resolved software stack including transitive dependencies. Also, Pipfile.lock states always pinned versions of all the libraries used (that are installed to run your application) including hashes for integrity checks.

**Comment by gsemet** [comment]
yes, that's for ensuring your build does not fail on change on pypi.
Then you need to declare the dependencies for your lib, that's the job of setup.py's install_requires, and for that I have my tool: https://pypi.org/project/pipenv-to-requirements/

**Comment by jerome-diver** [comment]
@fridex and @gsemet 
thank you for give time to explain
This make me understand better the idea about why to track Pipenv.lock file.

**Comment by fcovatti** [comment]
This has been 4 years long. From the security perspective there is to me a trade-off that I would like to understand if it makes sense for you as well:

1) Commit the Pipfile.lock makes sure that a specific hash is used for the package that will be installed, that is a good security functionality
2) But not committing the Pipfile.lock and using inclusive or exclusive version comparisons can make the package be always upgraded to latest version that will potentially have security fixes.

Which ones do you consider better? 

Here is my reasoning on option 2):
For example, in one project I have in the Pipfile:
`Django = "<4.0,>=3.2"`

But on the Pipfile.lock it was locked to 3.2.4 hash.

But there is a security vulnerability fixed in 3.2.5 Django version.
So due to committing the Pipfile.lock I was using a package version with a known CVE vulnerability.
If I do not version control the Pipfile.lock my Django version would be bumped to 3.2.7 automatically on the next CI/CD build of my latest docker image.

I came from the basic requirements.txt world and have a preference for option 2), could you please say what I may be missing here in terms of security for the recommendation to commit it?

**Comment by gsemet** [comment]
From a security point of view you should always take what is in the lock file, never try to update it silently. Remember project might not follow semver correctly. So what if 3.2.7 introduces itself a huge new bug…

so, update only on purpose with pipenv update. Maybe you want something like « pipenv update —bugfix-only », but again, you expect people to follow semver which is sadly not always the case

**Comment by fcovatti** [comment]
Totally understand, but I am trusting that my unit tests and system tests will catch a potential bug as I version control the build container with the 3.2.7 package and test the release before going into production.

I understand that if the network between my CI/CD server and pypi is compromised as I am not verifying the hash I could potentially install a insecure package.

I am just worry that not updating the versions and let it go to production with a known CVE due to the lock file and trusting developers will handle the pipenv update could be a potential security risk.

It seems the only way to go is to commit the pipfile.lock and avoid to create a release with known CVEs by using security scan of potential vulnerabilities in the pipenv.lock packages via another application. This could be a potential improvement in pipenv to inform that are packages in the pipfile.lock with known vulnerabilities.
