### ISSUE TITLE
pipenv install replaces underscore when writing in pipfile

### ISSUE THREAD

**Issue by thiezn** [kennethreitz/pipenv#629]
When installing a private repository using pipenv install (or from requirements.txt) it seems the Pipfile entry it creates replaces the underscore from '_git' with '-git':
 
```bash
pipenv install git+ssh://git@bla.com:22/tfs/E-CommerceIT/IaaS-PaaS/_git/mymodule#egg=mymodule
... truncated output ...
Adding git+ssh://git@bla.com:22/tfs/E-CommerceIT/IaaS-PaaS/_git/mymodule#egg=mymodule to Pipfile's [packages]…
```
```
cat Pipfile | grep mymodule
mymodule= {git = "ssh://git@bla.com:22/tfs/e-commerceit/iaas-paas/-git/mymodule"}
````

Manually editing the Pipfile and correcting the path allows me to use pipenv update. Note: I replaced the domain and package naming here in my examples.

**Comment by techalchemy** [comment]
@kennethreitz @nateprewitt this was a workaround for post-release versioning in pypi before we were using the pip resolver + fallbacks... the semver/pip-approved naming conventions store post releases in .post1 format, but I think the JSON api had trouble resolving them.  It's possible that we no longer have to manually correct this because we fall back to the pip/pip-tools resolver now.  Will investigate.

**Comment by kennethreitz** [comment]
this shouldn't be done to urls

**Comment by nateprewitt** [comment]
Yeah this is a normalization that's done specifically for uniformity in pypi packages because we were not detecting things like flask-common and flask_common being the same package. pep423 shouldn't be run on URLs because they can have case-sensitive paths and don't necessarily adhere to pypis interchangeability of - and _.

A PR to fix this would be very welcome!

**Comment by techalchemy** [comment]
It shouldn't be done to URLs I agree.  But I think we can also detect that those are the same package now because we use the pip resolver!

**Comment by kennethreitz** [comment]
i'll look into fixing this today

**Comment by nateprewitt** [comment]
Yeah, if you someone wants to put something together with tests, I'm all for removing this process. It was an unfortunately cludgy solution to the problem we were experiencing early in Pipenvs life cycle.

**Comment by kennethreitz** [comment]
what part of the code is this happening in?
