### ISSUE TITLE
Where did the estimated installation time go?

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#660]
I don't think I have my terminal colors configured in a strange way, but I haven't been able to see the estimated installation time since the install progress bar got all "fancy":

<img width="532" alt="screen shot 2017-09-22 at 8 55 30 pm" src="https://user-images.githubusercontent.com/939501/30768636-756e9a70-9fd8-11e7-84bf-c260c386d706.png">

**Comment by jacebrowning** [comment]
It used to be the same color as the `x/y` count.

**Comment by jacebrowning** [comment]
On this project I am using 6.x.

**Comment by kennethreitz** [comment]
It's black — which should be off-black in your terminal. This is only on Python 3.

**Comment by kennethreitz** [comment]
make your black a dark grey and everything will look much nicer :)

**Comment by jacebrowning** [comment]
I get why the unfilled boxes are "off-black", but why is the time estimate?

**Comment by jacebrowning** [comment]
FYI: I think I'm using one of the default iTerm themes.

**Comment by kennethreitz** [comment]
i believe i am as well.

**Comment by jacebrowning** [comment]
I can sort of see the estimate when that tab is in the background:

<img width="633" alt="screen shot 2017-09-22 at 9 50 00 pm" src="https://user-images.githubusercontent.com/939501/30769086-08d76286-9fe0-11e7-9f0f-7f16ff72461e.png">

**Comment by kennethreitz** [comment]
it's not going to change.

**Comment by joshfriend** [comment]
Readability of some of the other text with a light theme isn't so good either:

![asdf](https://i.imgur.com/QZ2UeOi.png)

(iTerm "Light Background")

**Comment by techalchemy** [comment]
Everyone should stop using themes which have illegible text colors configured. If you find yourself in this situation, tweak the colors of your theme. Your terminal theme should not allow text to be illegible.

**Comment by AlJohri** [comment]
`PIPENV_COLORBLIND` is always an option as well.

FWIW, I am also using the default iTerm2 preset which is default all black. I switched to 30% Grey which makes it more visible.

![screen shot 2017-09-23 at 1 06 23 pm](https://user-images.githubusercontent.com/2790092/30775368-160dc79e-a060-11e7-9427-a661d13b0a28.png)

**Comment by kennethreitz** [comment]
i recommend changing black, instead of your background.

**Comment by kennethreitz** [comment]
![](http://share.kennethreitz.org/221q0X2q2U1T/Screen%20Shot%202017-09-23%20at%203.18.05%20PM.png)

**Comment by kennethreitz** [comment]
![](http://share.kennethreitz.org/3N061i3Q2F2o/Screen%20Shot%202017-09-23%20at%203.18.20%20PM.png)

**Comment by techalchemy** [comment]
I find it amusing that people would give a 'thumbs down' for being given the advice to change a setting if it is resulting in a color you can't read.  Terminal colors are 100% in the control of your color theme.  If you picked a color theme that ignores the legibility of certain colors, then you need to fix it.

**Comment by joshfriend** [comment]
Because people should not have to know about how to configure ANSI colors in their terminal to figure out why they cannot read the output from a tool that is supposed to be easy to use.

**Comment by kennethreitz** [comment]
People should have properly configured terminals. If there's a way to detect that the background is white, i'm all ears. otherwise, it's staying.

**Comment by jacebrowning** [comment]
FWIW, I just set up a new MacBook with iTerm using the default theme and can't see some of the text. I think we're going to be dealing with thousands of users every month "using themes which have illegible text colors configured".

Maybe some would consider this a change request for iTerm, but if pipenv is to be ubiquitous, I think it should behave nicely in the the common cases.

**Comment by kennethreitz** [comment]
We've vastly improved this. The count-down timer is a nicety, and far from required. 

I'm more than fine with it only being shown to people who have their terminals nicely configured.

**Comment by kennethreitz** [comment]
Not to mention, it's far from accurate, so not showing it a lot of the time might be a feature, not a bug :)

**Comment by Pawamoy** [comment]
OK, I think I got the point: whatever color the developer chooses to use, this color should be visible in the end user terminal, **and it's the user responsibility indeed**. If the terminal provides a "black" color, then anyone should be free to use it when writing a program.

If you can't see the text because your background is the same color, then you need to change it. Maybe some day you will also want to use black color in a script/program you write: no other choice than making it more visible in your own terminal, right?

**Comment by untitaker** [comment]
I just started using pipenv and find the colors make its output completely unreadable. It's not only about the missing UI elements: I've seen many programs which look like pipenv, and it's always been a case of the developer testing on one particular colorscheme (often Solarized). But it's a new level of arrogance to not even acknowledge this bug and suggest that all other colorschemes are wrong.

If you want to argue that my color scheme is wrong, you can take that discussion up with the scheme's authors. Maybe you write a mailing list post somewhere to change the default colors of the Linux TTYs while you're out there. But as a user I certainly don't want to die on the hill of discussing whether black should really be black. I want to use a development tool for writing my Python program.

I guess I will set `PIPENV_COLORBLIND` before I become colorblind for real.

**Comment by mentalisttraceur** [comment]
Y'all realize terminals do more than just carefully pre-crafted themes right?

For example, some people do things like [randomized terminal background colors](https://scriptingosx.com/2019/12/random-terminal-background-colors/). We can imagine other use cases, like background commands changing terminal color to signal something to the user. Etc. Terminals are often flexible and programmatically controllable, and the range of uses is wide.

And it's fine if you just say "we don't wish to or simply cannot support those use cases, because they're too hard and variable to get right". Heck, you can even argue justifiably that a solution which changes terminal background colors ought to also change all the other standard colors too. You'd need to be compassionate for how that's inherently technically harder for a user, but it's a sound argument from a software design/engineering/architecture perspective.

But don't be dickishly dismissive just because the only use cases you can conceive of are ones where the obvious solution is to just configure black to be something other than literal black.

**Comment by mentalisttraceur** [comment]
Actually, it is wrong to assert that the users/themes are responsible for making all their foreground colors readable on the default background.

It is *just as defensible* to say that *the program* has the responsibility to *simultaneously change the background color* if it is changing the foreground color!

**Comment by mentalisttraceur** [comment]
When you come to a website you expect it to set the background color it needs. It would be considered unacceptable for a website to let your browser/user default CSS set the background color, hardcode black for the text color, and then blame you when it wasn't visible just because your user CSS is a dark theme.

This is admittedly further from the conventions we are used to with command-line tools - we don't expect a CLI tool to change the terminal background color for the duration of its entire output! - but it is not obviously or automatically wronger that way. Just different.

There are reasonable tradeoffs to this approach. Tools which change the terminal background color for the duration of their run need to be mindful to set it again after executing any external command which might also do so. On the other hand, this makes it vastly easier to see where the output of one command ends and the output of another command begins.

**Comment by mentalisttraceur** [comment]
Alternatively, **command-line tools that use color have the responsibility to be *themable***.

This is also pretty defensible. Maybe even more defensible than either of the other stated positions. It's not even technically hard, and it would give users flexibility to resolve problems like this while still freeing the default/preferred implementation to implicitly assert things like "if black is not visible on your background that's your problem".
