### ISSUE TITLE
Notification banner when using python 2

### ISSUE THREAD

**Issue by bobthebutcher** [kennethreitz/pipenv#745]
Mr Kenneth Sir,

Your projects have a massive reach across the python community. I was thinking about python 2 coming to and end and how to highlight the issue more as the date gets closer and closer. How would you feel about having some kind of banner when using pipenv with python2 ?

Something like;
NOTICE: Python 2 will be retired in 2020. It is recommended to migrate your applications to Python 3.
<insert helpful link here>

As the date gets closer the Notice could become more prominent. At some point you will probably drop support for py2 in this project that could also be incorporated into the notice.

Its just a thought, I can completely understand if you didn't want to have the additional overhead of managing something like this.

Thanks for your time and the awesome work on this project.

**Comment by nateprewitt** [comment]
Thanks for the idea @bobthebutcher! We are definitely in favor of moving people towards Python 3 and have made that the default for new environments.

While a banner may be helpful the first time someone sees it, I believe having it repeated every time a new Python 2 project is created will reduce the user experience. Some organizations and developers are unfortunately still shackled to Python 2 due to their dependencies. I'd rather not penalize them with more noise when they're aware of their situation.

Kenneth has added a banner pushing people towards using Python 3 to the Requests page, and we could possibly look at doing something on pipenv.org which I think would be more useful for reaching the desired audience.

I'll let Kenneth weigh in if he feels differently but I think this is something we won't be adding directly to the tool at this time. Thanks again for the suggestion though!

**Comment by kennethreitz** [comment]
correct.

**Comment by kennethreitz** [comment]
in 2019 we'll consider doing this.
