### ISSUE TITLE
Missing documentation on how to install in production enviroment

### ISSUE THREAD

**Issue by floqqi** [kennethreitz/pipenv#813]
I'm wondering there is no documentation on how to use pipenv in production deployment. My current setup for deploying something to production is like the following:

1. Pushing a new version of my package (as wheel) to my internal PyPi server (running [pypiserver](https://pypi.python.org/pypi/pypiserver))
2. Setting correct variables like `PIP_INDEX_URL` to my internal PyPi server on the target server
3. Running `pip install -U my-package` on the target server
4. Restart webserver

Having the list of requirements parsed from a `requirements.txt` into `install_requires` in my `setup.py`. The `requirements.txt` file is included by `MANIFEST.in`.

Now I'm courios if it is enough to include `Pipfile` and `Pipfile.lock` into my package and run `pipenv install` on the target production server? Does pipenv automatically use the environment variables like `PIP_INDEX_URL`? Or is `pip install -U my-package` still the preferred way? I know that there is `pipenv lock -r`, but I would like to abandon `requirements.txt` completely :)

**Comment by kennethreitz** [comment]
Pipfiles replace requirements.txt usage. They don't replace setup.py.

**Comment by exhuma** [comment]
@floqqi Have you found a solution? I'm using a similar setup as yours (except that I don't use `requirements.txt` at all.

I know that there is an important difference between `setup.py` and `requirements.txt`, in that the latter represents the concrete dependencies for a tested installation of the application and the former only gives "rough" package names.

I would love to do it "The Right Way", but from the existing documentation I really have trouble wrapping my head around how it is supposed to work. It's also not quite clear to me whether the `Pipfile` is actually meant to be used for prod? It works really well for development though.

**Comment by floqqi** [comment]
@exhuma No, not working with pipenv anymore. I continued pinning the versions in `requirements.txt` manually.

**Comment by techalchemy** [comment]
@floqqi sorry you had a bad experience, myself and lots of others use pipenv in production and need the functionality so while I am sorry, I’m also interested in productive comments :) hope you have a nice day

@exhuma the difference between `setup.py` and `requirements.txt` isn’t anything to do with whether one set of dependencies is concrete or not. Requirements.txt are used for two purposes kind of:

- Developing libraries and sharing with others what is needed to also develop those;
-  Tracking the exact stuff needed to create an environment for application deployments. 

The purpose of `setup.py` files is for distribution — they are how your application gets installed into other peoples environments, so not your application plus all of the extra stuff you decided to put into your environment, just your application, what’s needed to support it.

Now this is important because production is a pretty good use case for pipenv since you are trying to just recreate your development environment, roughly speaking. First you want to convert your `requirements.txt` to Pipenv. Then you can run `pipenv graph` and find your top level dependencies — this is basically what you want in your Pipfile. In your `Pipfile` you want to then start ‘unpinning’ those packages by changing from `package = “==x.y”` to `package = “*”`. Only do this for packages you actually don’t mind upgrading when possible. If there are any specific packages from `requirements.txt` where keeping their version is important you can pin those here too. 

Next you can just `pipenv install` — this creates the local copy of everything. If you want to include whatever your `setup.py` says, you can `pipenv install -e .`. This creates a `Pipfile.lock` which has pinned versions of every package in your environment. Every time you run `pipenv install` it updates this file.

When you are ready to deploy, you’ll want to include your `Pipfile` and `Pipfile.lock` and copy them with the rest of your project into production. Then, depending on your process, if you use docker and you don’t want a virtualenv to be created you will need to `pipenv install —system —deploy` but if you don’t use docker or you do want to have virtualenv creation and management, you can just `pipenv install —deploy`

Note that the `—deploy` flag simply says to fail if the lockfile and the Pipfile are not in sync, rather than attempting to sync them.

**Comment by exhuma** [comment]
@techalchemy  Thanks for the helpful reply. I've done a bit more reading in the mean-time but I am still not 100% clear about two things:

* I could use `Pipfile` for deployment. But when doing that I no longer have a package-file (`.whl` for example) to store in our package repository. I could still do that by using both `Pipfile` *and* a `setup.py` but then I don't really see a benefit in `Pipfile` anymore.
* What about `entry_points`?

And finally you say the following:

> The purpose of setup.py files is for distribution — they are how your application gets installed into other peoples environments, so not your application plus all of the extra stuff you decided to put into your environment, just your application, what’s needed to support it.

From my understanding the `Pipfile` is supposed to be just that? I fail to grasp the difference.

Maybe I am *really* slow about this. I had already trouble with the difference between `requirements.txt` and `setup.py`... But I have confidence in the pypa that they know their stuff better than me 😉 and would really wish to finally grok this once and for all... and I'm failing *hard* 😆 I would even be willing to talk about this in a hangout or Skype session 😄

**Comment by techalchemy** [comment]
Haha it is actually super nuanced and really annoying from a user perspective and until I was maintaining pipenv the difference want actually that clear to me either. It’s not just you. Pretty much everyone struggles with this. 

`setup.py` is for installing an application — what do I need to use this thing if I just want to flip the switch and hit go. `Pipfile` and `requirements.txt` are for installing development dependencies— what do I need to do dev work on this app. Of course you can blur the lines and lots of people do, but here’s why it matters:

If you put installation requirements in your `setup.py`, you can actually put your _application itself_ as a dependency in your Pipfile (`pipenv install -e .` would put it in editable mode which means your pipenv environment tracks updates you make to the codebase). This means that your application is the root dependency for the resolver, and conflict resolution becomes more consistent. Then you can put any development requirements in your `dev-packages` section (like pytest). Then maybe you need deployment specific packages that aren’t really project specific, you could include those in `packages` too. Then your resulting lockfile would install your project and it’s deployment dependencies when used in production, but keep those separate from the simple installation dependencies.
