### ISSUE TITLE
Disable prompt editing

### ISSUE THREAD

**Issue by toejough** [kennethreitz/pipenv#815]
Is there any way to disable prompt editing, or can that be added?  I like to maintain control of my terminal prompt, and with pyenv-virtualenv (on fish, at least), the prompt is not modified when activating a virtual-env, but with pipenv it is - it shows the full venv-name, including the random hash.

**Comment by erinxocon** [comment]
`pipenv shell --fancy` uses `pew` which doesn't modify your prompt.  My fish shell however includes functions that will show the virtualenv even when pew activates it.  On most *sh shells it shouldn't modify the prompt.  The reason it does now is because it's sourcing the activate.sh or in your case activate.fish which does include instructions to modify your prompt.
