### ISSUE TITLE
Scripts section in Pipfile

### ISSUE THREAD

**Issue by pablohenriq** [kennethreitz/pipenv#826]
Is there any way to have a scripts section where I can put, for example:
```
[scripts]
start = python main.py
```
And then, in my terminal, I can reproduce this through the command `pipenv run start`.

Any thoughts on that?

**Comment by kennethreitz** [comment]
not yet. thanks for the suggestion, though.

**Comment by kennethreitz** [comment]
I'll add a wiki page for this, under "potential ideas"

**Comment by kennethreitz** [comment]
documented here: https://github.com/kennethreitz/pipenv/wiki

**Comment by pablohenriq** [comment]
Very well. Thank you for the clarification.

**Comment by Place1** [comment]
Is there some kind of roadmap for features like this?  The scripts section in NPM projects is very useful for automating a project and allowing other devs to easily run the same scripts locally, with them all configured in 1 place.

**Comment by ryanhiebert** [comment]
I'll echo that sentiment. Right now I'm wondering where Tox has a place in my workflow. Right now it's just as a script runner, when I'm using Pipenv. There's still a place for Tox, but for a lot of my projects, the only thing I need more from Pipenv to drop Tox is to have scripts.

I was thinking about how I could build it as a separate thing, but the more I think about it the more I feel like it needs to be directly in Pipenv, because I'd probably end up trying to hack together a plugin (complete with monkeypatching) for the purpose, which sounds really ugly.

It's too bad that `run` was used for what it was. I probably would have called it `exec`, to leave `run` to better match the `npm run` mode of operation. I'm not sure of a good alternative name, so if it was my project (though that would be it's own bad idea), I'd want to rename it so I could use `run` for this purpose.

Yarn also allows scripts to run as just `yarn myscript`, which is cool, but seems magical. It's short and sweet, though.

**Comment by kennethreitz** [comment]
not happening, at this time

**Comment by kennethreitz** [comment]
unix philosophy, y'all

**Comment by kennethreitz** [comment]
FYI "npm does it" is not a good reason to do anything.

**Comment by kennethreitz** [comment]
i thank you for sharing though, it is very useful information

**Comment by Place1** [comment]
> unix philosophy, y'all

this seems like an odd argument given features such as:
- style checking
- security checking
- virtualenv management

are all in the scope of this project but could be considered more than just package management.

If the unix philosophy argument was to be applied to this project, then this project would just be pip. Pip does 'just one thing', manage packages. The point of this project (as i take it) is to expand on pip to be practical for real-world developers who need to do more than just install packages such as easily manage virtualenvs, manage project deps separately from all deps (lock file) and so on.

I think ignoring scripts misses an easy opportunity to help the python project tooling pain. The fact that NPM (and MANY other package managers) have this feature is somewhat relevant as those communities (many people) have decided the feature is useful. What is so unique about python development that we don't need project scripts?

> not happening, at this time

This leaves the option to the future which is great!

If this feature was to be added i'd like to see some of these points included:
- easy to remember command i.e: `pipenv launch [my_script] [...options passed to my_script]`
- should be launched using the virtualenv, even if the user forgot to run `pipenv shell`
- the specification of scripts should be single line strings that are executed in the shell.

**Comment by kennethreitz** [comment]
i really don't have the time or energy to discuss this, but i appreciate your thoughts

**Comment by kennethreitz** [comment]
so any comments left here will be for future :)

**Comment by naufraghi** [comment]
I just use [just](https://github.com/casey/just) for my commands, calling happily `pipenv run "some command"`, just one tool to learn for all different language projects.

**Comment by uranusjr** [comment]
So I happen to get myself here and kind of want to say something…

My basic stance is no, a script section is not needed. You see, tools like NPM has a script section not because this is a core feature, but they *need* it—there is no viable alternative anywhere in JavaScript, Ruby, etc. Python, on the other hand, has like 100 command runners available on PyPI (I’m probably vastly underestimating), including very mature, popular, and resourceful ones like Fabric and Invoke. There’s no need to go into this well-trotted field and add more fragmentation. You can just, say, add `invoke` to your `dev-packages`, and run your jobs with `pipenv run inv start`.

One thing I think that might be interesting though, is to do allow custom subcommands like Git does, e.g. `git mycoolcommand` automatically delegates to command `git-mycoolcommand` if there is one. This way people can start extending Pipenv with their own ideas, and if some prove to be extremely useful and popular Pipenv can always turn them into core subcommands.

**Comment by Place1** [comment]
I think npm scripts help against fragmentation. They give **all** js devs 1
place to look for project specific tooling/scripts which is its best
feature. People don’t want to learn everyone else’s script runner as they
bounce been projects.

**Comment by uranusjr** [comment]
NPM scripts reduce fragmentation because it is *the* standard tool people use for packaging. While Pipenv is officially recommended, it does not have the same status (I wholeheartedly hope it will one day). It might be able to reduce fragmentation when it does (like Python introduced `venv` in response to `virtualenv`), but now is not the time.

**Comment by AlJohri** [comment]
Just echoing the same sentiment. My use case here is nbextensions. I'd like to run this right after `pipenv install`.

```
pipenv run jupyter contrib nbextension install --sys-prefix --symlink
pipenv run jupyter nbextension enable --sys-prefix toc2/main
```

**Comment by kevlened** [comment]
For those still looking for a `scripts` section, it's [briefly documented under hidden features](https://github.com/pypa/pipenv/wiki#hidden-features)

**Comment by ekhaydarov** [comment]
@uranusjr I think the point is that it is all in one place which makes pipenv really good. Therefore it naturally makes sense for pipenv to also have scripts in the *same* place. It is really kind of your team to write some invoke scripts for the general use case but most use completely different scripts and will need to alter their commands. Doing it in the same file, same command is much more convenient that using other things. It also just builds up another dependency chain.

@kevlened thats a joke?

**Comment by kevlened** [comment]
@ekhaydarov No joke! I'm using in two repos now: https://github.com/browsertron/pytest-parallel/blob/master/Pipfile and https://github.com/kevlened/python-webdriver-stress-test/blob/master/Pipfile

`pipenv run NAME` will run the desired script

**Comment by kennethreitz** [comment]
You can have two pipfiles and specify the pipfile with `$ PIPENV_PIPFILE=./path/to/Pipfile.test pipenv run …`

**Comment by uranusjr** [comment]
For the record, it is also (briefly) documented in the docs. https://docs.pipenv.org/advanced/#custom-script-shortcuts

**Comment by jasonkuhrt** [comment]
Not possible to use `&&` however, e.g.:

```
"foo" = "echo 'a' && echo 'b'"
```

will not work

```
a && echo b
```

**Comment by uranusjr** [comment]
@jasonkuhrt `&&` is a shell-dependent syntax, so we avoid it to discourage people from writing things that are not cross-platform. (The same applies to output redirection.) Use a “proper” task runner if you want proper task scripting. (IMO every Python project should include either Fabric or Invoke.)

**Comment by jasonkuhrt** [comment]
@uranusjr I'm not willing to learn and include a new dependency to make up for one use case of `&&`. I will work around this in a much lighter weight way for the time being.

**Comment by sombriks** [comment]
by making scripts section a thing pipenv could match what Makefiles already does for years: not only being a build tool but also doubling as *executable documentation*. Also *npm/package.json does that* might be ugly but so true, this feature should be added in the near future.

**Comment by uranusjr** [comment]
I do have some improvements to the script section in mind, but haven’t found time to collect them into an enhancement proposal. Contact me (my email is listed on GitHub) if you are interested in writing and shepherding the proposal. I’d be happy to provide ideas and help with the implementation.
