### ISSUE TITLE
pipenv "--where" flag only works when initially creating the virtualenv

### ISSUE THREAD

**Issue by minskmaz** [kennethreitz/pipenv#838]
In a docker build pipeline the same virtualenv is often copied into multiple images. However when pipenv runs on an existing virtualenv (even after I've explicitly erased the Pipfile & Pipfile.lock) it will not report the path of the virtualenv. There are edge cases where multiple environments will be built in .virtualenvs so reporting this pathevery time pipenv install is run is important (at least to me). To be honest it's not even clear to me that the flag works at all.

**Comment by nateprewitt** [comment]
@minskmaz, it's somewhat unclear what you're asking here. If you don't have a Pipfile in your project, pipenv will treat this as a non-existent project. It sounds like you may be conflating the terms "project" (`--where`) and "virtual environment" (`--venv`) which are usually, but not always, separate locations. You can find the basics on Options on the homepage of http://pipenv.org or the Readme.md of this project.

If I'm missing something, please feel free to clarify your concerns. For the mean time, I'm closing this because it appears everything is working as expected.
