### ISSUE TITLE
Look for requirements.in when converting

### ISSUE THREAD

**Issue by ryanhiebert** [kennethreitz/pipenv#840]
pip-tools uses `requirements.in` like `Pipfile`, so that `requirements.txt` is like `Pipfile.lock`. When both are present, and pipenv wants to automatically create the Pipfile, it should use the `requirements.in` file instead of `requirements.txt`.

**Comment by kennethreitz** [comment]
Can you paste an example `requirements.in`?

**Comment by ryanhiebert** [comment]
Here's a scrubbed version of mine:

```
--extra-index-url https://pypi.fury.io/code/org/
-e git+https://github.com/tim-schilling/django-timezone-field.git@7d6eedee1ce2a1982ef2f32b2f9f1ef9e7e10651#egg=django-timezone-field
-e .
```

It's got the same format as a `requirements.txt`, but it doesn't lock the recursive dependencies the way the `requirements.txt` will after you run `pip-compile`.

**Comment by reupen** [comment]
Yes, essentially requirements.in is the unlocked dependencies, requirements.txt is locked using pip-compile.

Here is another pair of examples:
https://github.com/uktrade/data-hub-leeloo/blob/develop/requirements.in
https://github.com/uktrade/data-hub-leeloo/blob/develop/requirements.txt

**Comment by erinxocon** [comment]
Thanks for these!  Going to mark this as a future enhancement!

**Comment by bittner** [comment]
Mutual support would be cool, so that either tool could (at least) import, (maybe) auto detect, (optionally) convert, and compare + align with the other files. So, they could be used interchangeably, at developer's discretion.

Personally, just to give an example motivation, while I see `pipenv` to be the right path down harmonization with other languages and technologies, I do like the single-line simplicity of `requirements.txt` (and `requirements.in`) that [pip-tools](https://pypi.python.org/pypi/pip-tools/) is handling more.

**Comment by kennethreitz** [comment]
not happening

**Comment by bittner** [comment]
Thanks @kennethreitz! Can you give a little bit more detail, so everyone can understand why?

**Comment by frankier** [comment]
Yeah, I don't see mutual support as a useful feature or desirable in terms of the scope of either tool. Round tripping is messy. Pipfile seems strictly better to be so the migration path should be towards it (it's being standardised, so it's possibly you might use it with a tool other than pipenv in the future).

However, it would be cool if requiements.in projects could be migrated more smoothly.

It shouldn't be *too* hard since half of what's need can be done already quite easily:

    $ mv requirements.txt requirements.txt.lock
    $ mv requirements.in requirements.txt
    $ pipenv install

All that's missing at the point is the lock file should be based upon requirements.txt.lock instead of relocking the requirements. Even just doing something equivalent to the above (while issuing a warning about discarding locked versions) could be useful.
