### ISSUE TITLE
Uninstalling a dev package uninstalls all dev packages

### ISSUE THREAD

**Issue by SethMichaelLarson** [kennethreitz/pipenv#850]
I installed some packages to `dev-packages` then wanted to uninstall one of them. The result was that all packages in `dev-packages` were uninstalled.

### Steps to Reproduce

```
$ pipenv install --dev pytest pytest-flask
$ pipenv uninstall --dev pytest-flask
```

### Expected Pipfile
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pytest = "*"
```

### Actual Pipfile

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"
```

### Pipenv Version

```bash
$ pipenv --version
pipenv, version 8.2.6
```

**Comment by nateprewitt** [comment]
Hey @SethMichaelLarson, so I believe the --dev flag is documented as uninstalling everything. The reason it's not needed for uninstall is you can't have the same package in both packages and dev-packages. So simply using pipenv uninstall pytest-flake should be sufficient.

We have other issues discussing this before, but the consensus from the other maintainers has been things are working as intended.

**Comment by SethMichaelLarson** [comment]
Dang, so when you run `pipenv uninstall [package]` and it's in `requirements` and `dev-requirements` how does it decide? Uninstall both? I respect the decision of maintainers but it feels like a discrepancy between `install` and `uninstall`.

**Comment by nateprewitt** [comment]
Sorry for the delayed response here @SethMichaelLarson. This got bumped off my email queue somehow.

So the idea here is you would never have a specification for the same package in both `[package]` and `[dev-package]`. If you need it in `[package]`, the it *has to* be in your development environment because of how pipenv works. If you only need it in `[dev-package]`, then it shouldn't be in your `[package]` section for the previous reason.

The likelihood of those two separate version creating an unstable test environment means we previously enforced this inability to do this. It actually seems like this may have been regressed at some point while I've been away. I think the general reasoning still stands though, even if the railing isn't currently in place.

I'm not sure if @kennethreitz intentionally removed the safeguards for this, or if we need to look into readding something.
