### ISSUE TITLE
Make --three / --two more general

### ISSUE THREAD

**Issue by mrh1997** [kennethreitz/pipenv#885]
When specifiying --three / --two I would expect that it creates a Pipfile that enforces Python 3 / 2.
But in fact it enforces the concrete Python version installed on my computer.

Wouldn't it be clearer if the existing option ```--python <version>``` is used for that purpose while --three/--two is only used for specifing that Python 3 / 2 is enforced (without a specific version) or at least that my version is enforced at minimum?

Then I could use ```--python 3.6``` to enforce python 3.6, while I would use ```--three``` to enforce any python 3 environment (or any python 3 greater equal 3.6, if 3.6 is my local installation).

Or did I miss the real intention of the --two / --three / --python parameters?

**Comment by nateprewitt** [comment]
@mrh1997, thanks for opening an issue to start this discussion. The issue you're encountering is one that isn't nicely solved for all cases. There are trade offs for how we choose to select a python version.

Some users have older versions of Python 3 (3.1, 3.2, 3.3) bound to the `python3` symlink despite being deprecated because of their distro. This means given a generic `python3` specifier from a user on a system that has Python 3.5 as the default, won't necessarily work on their machine. Pipenv also officially only offers support for Python 2.7 so that means more ambiguous specificity isn't required there.

For those reasons, I don't see us moving back to a more generic model for `--two`/`--three` at this time. `--python` is a legacy artifact from a time when `--two`/`--three` were more generic but now still provides (I believe) the ability to specify down to a patch/hotfix version.

Let us know if you have any further thoughts, but I think that's where we're at for the time being. Cheers 🍻

**Comment by mrh1997** [comment]
I understand your comment regarding possible problems wth python 3.1-3.3. In fact this came already into my mind.

Thus I proposed alternatively to enforce **at least** the python version used locally.
If I work with 3.5 this would mean that it is ensured that this project requires 3.5 or higher.

This would ensure that when I checkout an old project (which was created with 3.4) would still be accepted on my PC with my brand new 3.7 installation. This would correspond to the concept of specifiying package versions, which are usually also specified in version ranges instead of fix versions.

**Comment by nateprewitt** [comment]
@mrh1997, I think it's technically possible for us to provide a `>=` option, but I believe @kennethreitz intent is for this to be a universally usable lockfile. That way people know things will work identically across machines. Having a range allows subtle variances to creep in and makes debugging build issues harder.

I'll defer to @kennethreitz if he has a different opinion on this, but I think at this time we're unlikely to introduce ambiguity around this specifier.

**Comment by anowlcalledjosh** [comment]
A `>=` operator for Python version in `Pipfile` would make sense, given that the requirements for packages in `Pipfile` are typically `"*"`. `Pipfile.lock` could have the most specific Python version possible to ensure reproducibility, but having `Pipfile` say simultaneously "just give me Flask, I don't care what version" and "I need exactly Python 3.6" doesn't make sense IMHO.

**Comment by mrh1997** [comment]
@anowlcalledjosh: In my experience my projects uses features (from flask/python/whatsoever) which are available only in specific versions (and higher).
Thus I usually say: "give me Flask with version >= X" and "give me Python >= Y".

pipenv has excellent support for specificing "give me Flask with version >= X" (```pipenv install flask>=X.Y.Z```). But for doing the same with the python version I had to modify the ```Pipfile``` manually, as ```--three``` enforces *any* Python 3 and ```--python 3.5``` enforces *exactly* 3.5 but does not accept 3.6.

**Comment by anowlcalledjosh** [comment]
@mrh1997 Yes, that's basically what I was trying to say – sorry I wasn't clear!
