### ISSUE TITLE
pipenv misses some dependencies during installs

### ISSUE THREAD

**Issue by walterdolce** [kennethreitz/pipenv#897]
Hi guys. I believe there is a bug somewhere in `pipenv` which is causing the behaviour highlighted here: fabric/fabric#1675.

In short, I had to manually specify a dependency of another dependency in my `Pipenv` file because someone (pipenv? virtualenv? something else?) wasn't able to see it and therefore import it while issuing CLI commands within the scope of a `pipenv shell` session.

Anything you need me to do to help troubleshoot this please let me know. Thank you in advance.

**Comment by techalchemy** [comment]
Can you show the output of `pipenv —version` and attempt a clean install (you can activate a new virtualenv or `pipenv —rm` the old one) using `pipenv install —verbose` and provide the pipfile in question and the output?

**Comment by bitprophet** [comment]
FWIW this may be something to do with wheels, as the sub-dependency is a conditional one which only appears if `setup.py` notices the installation Python version is `<3.4`. I haven't poked wheels in a while but I'm wondering what happens when the wheel-creating interpreter (in this case, that of the `cryptography` project - so this may end up being sent there?) is 3.4 or up - will it simply omit the `enum34` requirement, thus basically losing that info? Food for thought, anyways.

**Comment by vphilippon** [comment]
I'd put my money on another case of "wrong wheel used for dependencies resolving", which is fixed in 8.2.7.

What likely happened is that a Py3.4+ wheel of `cryptography` was selected for listing the dependencies (even if the environment was Py2, that's the bug), which didn't list `enum34` as a dependency (as its only needed for Py<3.4). Then, when installing, `pipenv` strictly installed what was in Pipfile.lock (using the equivalent of `pip install --no-deps`), assuming the Pipfile.lock included all the right dependencies, which wasn't the case due to the bug. This is how `enum34` ended up missing in the environment, causing the `ImportError`.

Could you to `pipenv` 8.2.7, lock with a cleared cache (`pipenv lock --clear`), and confirm if its fixed?

**Comment by techalchemy** [comment]
@bitprophet yeah I don't think the wheels are bad or I certainly didn't mean to imply that.  As @vphilippon mentioned I was thinking it was likely an issue with dependency resolution which is something I know has been an ongoing challenge and was being actively worked on.  He pretty much covered the likely culprit and the fix, so I'm guessing this is resolved

**Comment by bitprophet** [comment]
@techalchemy oh, wasn't meaning to imply you were saying that, my whole comment was thinking out loud! :)

@vphilippon That sounds like it would perfectly fit the issue as described by the OP. I'll let him report back, I've only been the messenger so far. Thanks for the response!

**Comment by erinxocon** [comment]
Closing this in favor of issue #914 :)
