### ISSUE TITLE
Pipenv does not always works out of your current directory

### ISSUE THREAD

**Issue by davidssonarnor** [kennethreitz/pipenv#900]
If you have a Pipfile in the root directory Pipenv will work out from that directory. Was incredibly annoying until I realised what the problem was. I am using pipenv, version 8.2.7.

**Comment by nateprewitt** [comment]
@davidsonarnor, it's not entirely clear what you're asking here.

Pipenv will use its closest Pipfile within PIPENV_MAX_DEPTH (a configurable environment var) hops *up* from the current directory. If you wish to force use of only your current directory, you'll need to set that to 1.

If you had a virtualenv already activated, pipenv will use that over creating one for your current directories project. This is also intended and we warn for it when populating the environment.

I'm currently not sure if there is a defect here. I'm closing this for now since things appear to be working and these features are documented. Please let us know if we're missing something though and we can reopen this. Thanks!
